// src/features/shopping-list/component/cart-item.tsx
import { UNITS, type UnitSlug } from '@schema'
import { cn } from 'cn'
import { useState } from 'react'

import { CheckIcon } from '@/components/icons'
import { formatNumber } from '@/utils/number'

import { type IngredientCartItem } from '../types/ingredient-cart-item'

const formatUnitLabel = (slug: UnitSlug | null) => (slug ? (UNITS[slug]?.name ?? '') : '')

const formatQuantityWithUnit = (quantity: number, unitSlug: UnitSlug | null) => {
  const label = formatUnitLabel(unitSlug)
  return label ? `${formatNumber(quantity)} ${label}` : formatNumber(quantity)
}

export const CartItem = ({ ingredient }: { ingredient: IngredientCartItem }) => {
  const [isChecked, setIsChecked] = useState(false)

  return (
    <button
      type="button"
      onClick={() => setIsChecked((checked) => !checked)}
      className="flex w-full items-center gap-3 border-b py-3 text-left last:border-b-0"
    >
      <span
        className={cn(
          'flex size-5.5 shrink-0 items-center justify-center rounded-full border-2',
          isChecked ? 'border-primary bg-primary text-white' : 'border-muted-foreground/40'
        )}
      >
        {isChecked && <CheckIcon weight="bold" className="size-3" />}
      </span>
      <span className={cn('flex flex-1 items-center justify-between gap-2', isChecked && 'text-muted-foreground line-through')}>
        <span>{ingredient.name}</span>
        <span className="flex flex-col items-end text-sm font-semibold text-muted-foreground tabular-nums">
          <span>{formatQuantityWithUnit(ingredient.primary.quantity, ingredient.primary.unitSlug)}</span>
          {ingredient.fallback.map((line) => (
            <span className="text-xs" key={line.unitSlug ?? 'unitless'}>
              + {formatQuantityWithUnit(line.quantity, line.unitSlug)}
            </span>
          ))}
        </span>
      </span>
    </button>
  )
}

// src/features/shopping-list/client/component/cart-item.svelte
<script lang="ts">
  import Toggle from '@/components/ui/actions/toggle/toggle.svelte'
  import { formatNumber } from '@/utils/number'
  import { UNITS } from '@/utils/units'
  import type { UnitSlug } from '@/utils/units'

  import type { IngredientCartItem } from '../types/ingredient-cart-item'

  const { ingredient }: { ingredient: IngredientCartItem } = $props()
  let isChecked = $state(false)
  const formatQuantityWithUnit = (quantity: number, unitSlug: UnitSlug | null) => {
    const label = unitSlug ? (UNITS[unitSlug]?.name ?? '') : ''
    return label ? `${formatNumber(quantity)} ${label}` : formatNumber(quantity)
  }
</script>

<Toggle onPressedChange={(pressed) => (isChecked = pressed)} presentation="check-row" pressed={isChecked}>
  <span class="cart-item-details">
    <span>{ingredient.name}</span>
    <span class="cart-item-quantities">
      <span>{formatQuantityWithUnit(ingredient.primary.quantity, ingredient.primary.unitSlug)}</span>
      {#each ingredient.fallback as line (line.unitSlug ?? 'unitless')}
        <span class="cart-item-fallback-quantity">+ {formatQuantityWithUnit(line.quantity, line.unitSlug)}</span>
      {/each}
    </span>
  </span>
</Toggle>

<style>
  .cart-item-details {
    align-items: center;
    display: flex;
    flex: 1;
    gap: 8px;
    justify-content: space-between;
  }

  .cart-item-quantities {
    align-items: flex-end;
    color: var(--colors-muted-foreground);
    display: flex;
    flex-direction: column;
    font-size: var(--font-sizes-sm);
    font-variant-numeric: tabular-nums;
    font-weight: var(--font-weights-semibold);
  }

  .cart-item-fallback-quantity {
    font-size: var(--font-sizes-xs);
  }
</style>
