// src/components/app-shell/theme-toggle.tsx
import { Button } from '@/components/ui/actions/button/button'
import { ThemeIcon } from '@/components/ui/data-display/icons'
import { toggleTheme } from '@/lib/client/theme'

export const ThemeToggle = () => (
  <Button aria-label="Changer de thème" onClick={toggleTheme} size="icon" variant="ghost">
    <ThemeIcon size="lg" />
  </Button>
)

// src/components/app-shell/theme-toggle.svelte
<script lang="ts">
  import Button from '@/components/ui/actions/button/button.svelte'
  import { ThemeIcon } from '@/components/ui/data-display/icons'
  import { toggleTheme } from '@/lib/client/theme'
</script>

<Button aria-label="Changer de thème" onclick={toggleTheme} size="icon" variant="ghost">
  <ThemeIcon size="lg" />
</Button>
