// src/components/forms/text-field.tsx
import { Show } from 'solid-js'

import { Field, FieldError, FieldLabel } from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { useFieldContext } from '@/hooks/use-form-context'

interface TextFieldProps {
  class?: string
  disabled?: boolean
  label?: string
  placeholder?: string
}

export const TextField = (props: TextFieldProps) => {
  const field = useFieldContext<string>()

  return (
    <Field
      class={props.class}
      dirty={field().state.meta.isDirty}
      invalid={!field().state.meta.isValid}
      name={field().name}
      touched={field().state.meta.isTouched}
    >
      <Show when={props.label}>{(label) => <FieldLabel>{label()}</FieldLabel>}</Show>
      <Input
        disabled={props.disabled}
        onInput={(event) => field().handleChange(event.currentTarget.value)}
        placeholder={props.placeholder}
        value={field().state.value}
      />
      <FieldError />
    </Field>
  )
}

// src/components/ui/forms/text-field/text-field.tsx
import { useId } from 'react'

import { useFieldContext } from '@/hooks/use-form-context'

import { Field, FieldError, FieldLabel } from '../field/field'
import { Input } from '../input/input'

export interface TextFieldProps {
  disabled?: boolean
  label?: string
  placeholder?: string
}

export const TextField = ({ disabled, label, placeholder }: TextFieldProps) => {
  const field = useFieldContext<string>()
  const id = useId()

  return (
    <Field invalid={!field.state.meta.isValid} name={field.name}>
      {label && <FieldLabel htmlFor={id}>{label}</FieldLabel>}
      <Input
        aria-invalid={!field.state.meta.isValid || undefined}
        disabled={disabled}
        id={id}
        onChange={(event) => field.handleChange(event.target.value)}
        placeholder={placeholder}
        value={field.state.value}
      />
      <FieldError />
    </Field>
  )
}
