// pages/recipe/new/index.svelte
<script lang="ts">
  import { useForm, useRouter } from '@void/svelte'

  import GoBackButton from '@/components/screen-layout/go-back-button.svelte'
  import ScreenLayout from '@/components/screen-layout/screen-layout.svelte'
  import Button from '@/components/ui/actions/button/button.svelte'
  import FormSubmit from '@/components/ui/forms/form-submit/form-submit.svelte'
  import Form from '@/components/ui/forms/form/form.svelte'
  import { renderAddIngredientOption } from '@/features/ingredients/client/components/add-ingredient.svelte'
  import { provideIngredientCatalog } from '@/features/ingredients/client/contexts/ingredient-catalog-context.svelte'
  import { useIngredientOptions } from '@/features/ingredients/client/hooks/use-ingredient-options.svelte'
  import RecipeFormActions from '@/features/recipe/client/components/recipe-form-actions.svelte'
  import type { RecipeFormState } from '@/features/recipe/client/components/recipe-form.svelte'
  import RecipeForm from '@/features/recipe/client/components/recipe-form.svelte'
  import { provideRecipeCatalog } from '@/features/recipe/client/contexts/recipe-catalog-context.svelte'
  import { recipeDefaultValues } from '@/features/recipe/client/utils/form'
  import { alertError } from '@/lib/client/alert-error'
  import { useFormActionError } from '@/lib/client/page-action.svelte'

  import type { Props } from './index.server'

  const { ingredients, recipes }: Props = $props()
  provideIngredientCatalog(() => ingredients)
  provideRecipeCatalog(() => recipes)
  const ingredientOptions = useIngredientOptions()
  const router = useRouter()

  const form = useForm('/recipe/new', recipeDefaultValues)
  const errorMessage = () => `Erreur lors de la création de la recette ${form.data.name ?? ''}`
  useFormActionError(() => form.error, errorMessage)
  const recipeForm: RecipeFormState = {
    get data() {
      return form.data
    },
    get pending() {
      return form.pending
    },
    setData: (key, value) => {
      form.data[key] = value
    },
  }

  const submit = async (event: SubmitEvent) => {
    event.preventDefault()
    if (form.pending) {
      return
    }
    try {
      await form.post()
      if (form.wasSuccessful) {
        await router.visit('/', { replace: true })
      }
    } catch (error) {
      alertError(errorMessage(), error)
    }
  }
</script>

<ScreenLayout title="Nouvelle Recette">
  <Form errors={form.errors} onsubmit={submit}>
    <RecipeForm addNewIngredientOption={renderAddIngredientOption} form={recipeForm} ingredientOptions={ingredientOptions.current} />
    <RecipeFormActions>
      <Button disabled={form.pending} onclick={() => router.visit('/')} type="button" variant="outline">Annuler</Button>
      <FormSubmit pending={form.pending} label="Créer la recette" />
    </RecipeFormActions>
  </Form>
  {#snippet backButton()}<GoBackButton />{/snippet}
</ScreenLayout>

// apps/web/src/routes/recipe/new.tsx
import { getIngredientListOptions } from '@client/features/ingredients/api/get-all'
import { renderAddIngredientOption } from '@client/features/ingredients/components/add-ingredient'
import { useIngredientOptions } from '@client/features/ingredients/hooks/use-ingredient-options'
import { createRecipeOptions, recipeSchema } from '@client/features/recipe/api/create'
import { getRecipeListOptions } from '@client/features/recipe/api/get-all'
import { RecipeForm } from '@client/features/recipe/components/recipe-form'
import { RecipeFormActions } from '@client/features/recipe/components/recipe-form-actions'
import { recipeDefaultValues, recipeFormFields } from '@client/features/recipe/utils/form'
import { Button } from '@recipe-organizer/design-system/button'
import { Form } from '@recipe-organizer/design-system/form'
import { useAppForm } from '@recipe-organizer/design-system/hooks/use-app-form'
import { ScreenLayout } from '@recipe-organizer/design-system/screen-layout'
import { formatFormErrors } from '@recipe-organizer/design-system/utils/format-form-errors'
import { objectToFormData } from '@recipe-organizer/shared/utils/form-data'
import { revalidateLogic } from '@tanstack/react-form'
import { useMutation } from '@tanstack/react-query'
import { createFileRoute, redirect, useRouter } from '@tanstack/react-router'
import { useSelector } from '@tanstack/react-store'

const NewRecipePage = () => {
  const router = useRouter()
  const { mutateAsync: createRecipe } = useMutation(createRecipeOptions())
  const ingredientOptions = useIngredientOptions()

  const form = useAppForm({
    defaultValues: recipeDefaultValues,
    onSubmit: async ({ value }) => {
      const formData = objectToFormData(value)
      await createRecipe({ data: formData })

      await router.navigate({ to: '/' })
    },
    validationLogic: revalidateLogic(),
    validators: {
      onDynamic: recipeSchema,
    },
  })

  const errors = useSelector(form.store, (state) => formatFormErrors(state.errors))

  return (
    <ScreenLayout title="Nouvelle Recette" withGoBack>
      <Form
        errors={errors}
        onSubmit={(event) => {
          event.preventDefault()
          void form.handleSubmit()
        }}
      >
        <RecipeForm addNewIngredientOption={renderAddIngredientOption} fields={recipeFormFields} form={form} ingredientOptions={ingredientOptions} />
        <RecipeFormActions>
          <Button disabled={form.state.isSubmitting} onClick={() => router.navigate({ to: '/' })} type="button" variant="outline">
            Annuler
          </Button>
          <form.AppForm>
            <form.FormSubmit label="Créer la recette" />
          </form.AppForm>
        </RecipeFormActions>
      </Form>
    </ScreenLayout>
  )
}

export const Route = createFileRoute('/recipe/new')({
  beforeLoad: ({ context }) => {
    if (!context.authUser) {
      throw redirect({ from: '/recipe/new', to: '/auth/login' })
    }
  },
  component: NewRecipePage,
  loader: async ({ context }) => {
    await context.queryClient.query({ ...getIngredientListOptions(), staleTime: 'static' })
    await context.queryClient.query({ ...getRecipeListOptions(), staleTime: 'static' })
  },
})
