// apps/web/src/features/ingredients/components/delete-ingredient.tsx
import { DeleteDialog } from '@client/components/dialogs/delete-dialog'
import { deleteIngredientOptions } from '@client/features/ingredients/api/delete'
import { useMutation } from '@tanstack/react-query'

interface DeleteIngredientProps {
  ingredientId: number
  ingredientName: string
}

export const DeleteIngredient = ({ ingredientId, ingredientName }: DeleteIngredientProps) => {
  const deleteMutation = useMutation(deleteIngredientOptions())

  const handleDelete = () => deleteMutation.mutate({ data: { id: ingredientId } })

  return (
    <DeleteDialog
      description={`Êtes-vous sûr de vouloir supprimer l'ingrédient ${ingredientName} ?`}
      onDelete={handleDelete}
      title="Supprimer l'ingrédient"
    />
  )
}

// src/features/ingredients/client/components/delete-ingredient.svelte
<script lang="ts">
  import DeleteDialog from '@/components/ui/overlays/delete-dialog/delete-dialog.svelte'
  import { alertError } from '@/lib/client/alert-error'
  import { usePageAction } from '@/lib/client/page-action.svelte'

  const { ingredientId, ingredientName }: { ingredientId: number; ingredientName: string } = $props()
  const runPageAction = usePageAction()
  const handleDelete = async () => {
    try {
      await runPageAction('/settings/ingredients?delete', { data: { id: ingredientId } }, "Erreur lors de la suppression de l'ingrédient")
    } catch (error) {
      alertError("Erreur lors de la suppression de l'ingrédient", error)
    }
  }
</script>

<DeleteDialog
  description={`Êtes-vous sûr de vouloir supprimer l'ingrédient ${ingredientName} ?`}
  onDelete={handleDelete}
  title="Supprimer l'ingrédient"
/>
