// src/components/ui/forms/input/input.svelte
<script module lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'

  export type InputProps = Pick<
    HTMLInputAttributes,
    'aria-invalid' | 'aria-describedby' | 'aria-label' | 'disabled' | 'id' | 'name' | 'oninput' | 'placeholder' | 'required' | 'type' | 'value'
  > & { defaultValue?: HTMLInputAttributes['value'] }
</script>

<script lang="ts">
  import * as surface from './input-surface.css'
  import * as styles from './input.css'

  const { defaultValue, value, ...rest }: InputProps = $props()
</script>

<span class={surface.inputSurface} data-slot="input-control"
  ><input {...rest} value={value ?? defaultValue} class={styles.input} data-slot="input" /></span
>

// packages/design-system/src/ui/forms/input/input.tsx
import { Input as InputPrimitive } from '@base-ui/react/input'
import type React from 'react'

import * as surface from './input-surface.css'
import * as styles from './input.css'

export type InputProps = Pick<
  InputPrimitive.Props,
  'aria-invalid' | 'aria-label' | 'defaultValue' | 'disabled' | 'onChange' | 'placeholder' | 'type' | 'value'
>

export const Input = ({
  'aria-invalid': ariaInvalid,
  'aria-label': ariaLabel,
  defaultValue,
  disabled,
  onChange,
  placeholder,
  type,
  value,
}: InputProps): React.ReactElement => (
  <span className={surface.inputSurface} data-slot="input-control">
    <InputPrimitive
      aria-invalid={ariaInvalid}
      aria-label={ariaLabel}
      className={styles.input}
      data-slot="input"
      defaultValue={defaultValue}
      disabled={disabled}
      onChange={onChange}
      placeholder={placeholder}
      type={type}
      value={value}
    />
  </span>
)
