// packages/design-system/src/ui/forms/search-input/search-input.tsx
import { MagnifyingGlassIcon } from '@recipe-organizer/design-system/icons'

import * as styles from './search-input.css'

export interface SearchInputProps {
  autoFocus?: boolean
  placeholder?: string
  search: string
  setSearch: (value: string) => void
}

export const SearchInput = ({ autoFocus, placeholder = 'Rechercher…', search, setSearch }: SearchInputProps) => (
  <div className={styles.root} data-slot="input-group" role="group">
    <input
      aria-label={placeholder}
      autoFocus={autoFocus}
      className={styles.input}
      data-slot="input"
      onChange={(event) => setSearch(event.target.value)}
      placeholder={placeholder}
      value={search}
    />
    <div
      className={styles.addon}
      data-slot="input-group-addon"
      onMouseDown={(event) => {
        event.preventDefault()
        event.currentTarget.parentElement?.querySelector<HTMLInputElement>('input')?.focus()
      }}
    >
      <span className={styles.text}>
        <MagnifyingGlassIcon />
      </span>
    </div>
  </div>
)

// src/components/ui/forms/search-input/search-input.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import { MagnifyingGlassIcon } from '@/components/ui/data-display/icons/svelte'

  import * as styles from './search-input.css'

  const {
    autoFocus,
    placeholder = 'Rechercher…',
    search,
    setSearch,
  }: { autoFocus?: boolean; placeholder?: string; search: string; setSearch: (value: string) => void } = $props()
  let input: HTMLInputElement | undefined = undefined
  onMount(() => {
    if (autoFocus) {
      input?.focus()
    }
  })
</script>

<div class={styles.root} data-slot="input-group" role="group">
  <input
    aria-label={placeholder}
    bind:this={input}
    class={styles.input}
    data-slot="input"
    oninput={(event) => setSearch(event.currentTarget.value)}
    {placeholder}
    value={search}
  />
  <div
    class={styles.addon}
    data-slot="input-group-addon"
    aria-hidden="true"
    onmousedown={(event) => {
      event.preventDefault()
      input?.focus()
    }}
  >
    <span class={styles.text}><MagnifyingGlassIcon /></span>
  </div>
</div>
