// src/features/search/client/components/recipe-search.svelte
<script lang="ts">
  import { EMPTY_FILTERS, filterRecipes, hasActiveFilters } from '@/features/search/client/utils/filter'
  import type { SearchFilters as SearchFiltersValue } from '@/features/search/client/utils/filter'
  import type { ReducedRecipe } from '@/types/recipe'

  import RecentRecipes from './recent-recipes.svelte'
  import SearchFilters from './search-filters.svelte'
  import SearchResults from './search-results.svelte'

  const { recipes }: { recipes: ReducedRecipe[] } = $props()
  let filters = $state<SearchFiltersValue>(EMPTY_FILTERS)
  const filtered = $derived(filterRecipes(recipes, filters))
  const nonSpiceRecipes = $derived(recipes.filter((recipe) => !recipe.isSpice))
</script>

<SearchFilters {filters} onFiltersChange={(value) => (filters = value)} />
{#if hasActiveFilters(filters)}
  <SearchResults onClearFilters={() => (filters = EMPTY_FILTERS)} recipes={filtered} />
{:else}
  <RecentRecipes recipes={nonSpiceRecipes} />
{/if}

// src/features/search/client/components/recipe-search.tsx
import { useState } from 'react'

import { RecentRecipes } from '@/features/search/client/components/recent-recipes'
import { SearchFilters } from '@/features/search/client/components/search-filters'
import { SearchResults } from '@/features/search/client/components/search-results'
import { EMPTY_FILTERS, filterRecipes, hasActiveFilters } from '@/features/search/client/utils/filter'
import type { SearchFilters as SearchFiltersValue } from '@/features/search/client/utils/filter'
import type { ReducedRecipe } from '@/types/recipe'

export const RecipeSearch = ({ recipes }: { readonly recipes: ReducedRecipe[] }) => {
  const [filters, setFilters] = useState<SearchFiltersValue>(EMPTY_FILTERS)
  const filtered = filterRecipes(recipes, filters)
  const nonSpiceRecipes = recipes.filter((recipe) => !recipe.isSpice)

  return (
    <>
      <SearchFilters filters={filters} onFiltersChange={setFilters} />
      {hasActiveFilters(filters) ? (
        <SearchResults onClearFilters={() => setFilters(EMPTY_FILTERS)} recipes={filtered} />
      ) : (
        <RecentRecipes recipes={nonSpiceRecipes} />
      )}
    </>
  )
}
