// src/features/search/components/search-filters.tsx
import { FunnelSimpleIcon } from '@phosphor-icons/react'
import { useState } from 'react'

import { ToggleGroup } from '@/components/common/toggle-group'
import { SearchInput } from '@/components/search-input'
import { Button } from '@/components/ui/button'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { MAGIMIX_LABEL, VEGETARIAN_LABEL } from '@/features/recipe/utils/constants'

import { hasActiveFilters, type SearchFilters as SearchFiltersValue } from '../utils/filter'
import { CategorySelect } from './category-select'

const flagItems = [
  { label: VEGETARIAN_LABEL, value: 'isVegetarian' },
  { label: MAGIMIX_LABEL, value: 'isMagimix' },
]

interface SearchFiltersProps {
  filters: SearchFiltersValue
  onFiltersChange: (filters: SearchFiltersValue) => void
}

export const SearchFilters = ({ filters, onFiltersChange }: SearchFiltersProps) => {
  const [open, setOpen] = useState(false)

  const activeFlags = [filters.isVegetarian ? 'isVegetarian' : null, filters.isMagimix ? 'isMagimix' : null].filter((flag) => flag !== null)
  const hasFilters = hasActiveFilters({ ...filters, query: '' })

  const handleFlagsChange = (flags: string[]) =>
    onFiltersChange({ ...filters, isMagimix: flags.includes('isMagimix'), isVegetarian: flags.includes('isVegetarian') })

  return (
    <Collapsible onOpenChange={setOpen} open={open}>
      <div className="flex items-center gap-2">
        <div className="flex-1">
          <SearchInput autoFocus search={filters.query} setSearch={(query) => onFiltersChange({ ...filters, query })} />
        </div>
        <CollapsibleTrigger render={<Button aria-label="Filtrer par catégorie" size="icon-lg" variant={hasFilters ? 'default' : 'outline'} />}>
          <FunnelSimpleIcon />
        </CollapsibleTrigger>
      </div>
      <CollapsibleContent className="flex flex-wrap items-center gap-2 pt-2">
        <CategorySelect
          cuisineTypes={filters.cuisineTypes}
          meals={filters.meals}
          onCuisineTypesChange={(cuisineTypes) => onFiltersChange({ ...filters, cuisineTypes })}
          onMealsChange={(meals) => onFiltersChange({ ...filters, meals })}
        />
        <ToggleGroup items={flagItems} onValueChange={handleFlagsChange} value={activeFlags} />
      </CollapsibleContent>
    </Collapsible>
  )
}

// src/features/search/client/components/search-filters.svelte
<script lang="ts">
  import Button from '@/components/ui/actions/button/button.svelte'
  import Toggle from '@/components/ui/actions/toggle/toggle.svelte'
  import { FunnelSimpleIcon } from '@/components/ui/data-display/icons'
  import SearchInput from '@/components/ui/forms/search-input/search-input.svelte'
  import Select from '@/components/ui/forms/select/select.svelte'
  import { CUISINE_TYPE_LABELS, CUISINE_TYPES, MEAL_LABELS, MEALS } from '@/features/recipe/constants'
  import type { SearchFilters } from '@/features/search/client/utils/filter'

  import * as styles from './search-filters.css'

  const cuisineItems = CUISINE_TYPES.map((cuisineType) => ({ label: CUISINE_TYPE_LABELS[cuisineType], value: cuisineType }))
  const mealItems = MEALS.map((meal) => ({ label: MEAL_LABELS[meal], value: meal }))
  const { filters, onFiltersChange }: { filters: SearchFilters; onFiltersChange: (filters: SearchFilters) => void } = $props()
  let open = $state(false)
</script>

<div class={styles.container}>
  <div class={styles.searchInputRow}>
    <div class={styles.queryField}>
      <SearchInput
        placeholder="Rechercher une recette, un ingrédient…"
        autoFocus
        search={filters.query}
        setSearch={(query) => onFiltersChange({ ...filters, query })}
      />
    </div>
    <Button aria-label="Filtrer par catégorie" onclick={() => (open = !open)} size="icon-lg" variant="outline"><FunnelSimpleIcon /></Button>
  </div>
  {#if open}
    <div class={styles.element}>
      <div class={styles.mealFilter}>
        <Select
          items={mealItems}
          onValueChange={(meal) => onFiltersChange({ ...filters, meals: meal ? [meal] : [] })}
          placeholder="Repas"
          title="Repas"
          value={filters.meals[0]}
        />
      </div>
      <div class={styles.cuisineFilter}>
        <Select
          items={cuisineItems}
          onValueChange={(cuisineType) => onFiltersChange({ ...filters, cuisineTypes: cuisineType ? [cuisineType] : [] })}
          placeholder="Cuisines"
          title="Cuisines"
          value={filters.cuisineTypes[0]}
        />
      </div>
      <Toggle
        presentation="filter"
        variant="outline"
        pressed={filters.isVegetarian}
        onPressedChange={(isVegetarian) => onFiltersChange({ ...filters, isVegetarian })}>Végétarien</Toggle
      >
      <Toggle
        presentation="filter"
        variant="outline"
        pressed={filters.isMagimix}
        onPressedChange={(isMagimix) => onFiltersChange({ ...filters, isMagimix })}>Magimix</Toggle
      >
      <div class={styles.spiceFilter}>
        <Toggle
          presentation="filter"
          variant="outline"
          pressed={filters.isSpice}
          onPressedChange={(isSpice) => onFiltersChange({ ...filters, isSpice })}>Épices</Toggle
        >
      </div>
    </div>
  {/if}
</div>
