// src/design-system/ui/actions/button/button.tsx
import type { RecipeVariants } from '@vanilla-extract/recipes'
import { Link } from '@void/react'
import type React from 'react'
import type { ComponentProps } from 'react'

import * as styles from './button.css'

export type ButtonProps = Pick<ComponentProps<'button'>, 'aria-label' | 'children' | 'disabled' | 'type'> &
  RecipeVariants<typeof styles.button> &
  (
    | ({ asLink: true; onClick?: never } & Pick<ComponentProps<typeof Link>, 'href' | 'viewTransition'>)
    | ({ asLink?: false; href?: never; viewTransition?: never } & Pick<
        ComponentProps<'button'>,
        'aria-expanded' | 'aria-haspopup' | 'onClick' | 'onPointerDown' | 'ref'
      >)
  )

export const Button = (props: ButtonProps): React.ReactElement => {
  if (props.asLink) {
    const { align, asLink: _asLink, size, variant, width, ...linkProps } = props
    return <Link {...linkProps} className={styles.button({ align, size, variant, width })} />
  }

  const { align, asLink: _asLink, size, variant, width, ...buttonProps } = props
  return <button {...buttonProps} className={styles.button({ align, size, variant, width })} />
}

// src/components/ui/actions/button/button.svelte
<script lang="ts">
  import type { RecipeVariants } from '@vanilla-extract/recipes'
  import { Link } from '@void/svelte'
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  import * as styles from './button.css'

  type ButtonProps = Pick<HTMLButtonAttributes, 'aria-label' | 'disabled' | 'type'> &
    RecipeVariants<typeof styles.button> & { children?: Snippet } & (
      | { asLink: true; href: string; onclick?: never; ref?: never; viewTransition?: boolean }
      | ({ asLink?: false; href?: never; ref?: HTMLButtonElement; viewTransition?: never } & Pick<
          HTMLButtonAttributes,
          'aria-expanded' | 'aria-haspopup' | 'onclick' | 'onpointerdown'
        >)
    )

  let { align, asLink, children, href, ref = $bindable(), size, variant, viewTransition, width, ...rest }: ButtonProps = $props()
  const className = $derived(styles.button({ align, size, variant, width }))
</script>

{#if asLink && href !== undefined}
  <Link {...rest} class={className} {href} {viewTransition}>{@render children?.()}</Link>
{:else}
  <button {...rest} bind:this={ref} class={className}>{@render children?.()}</button>
{/if}
