// src/features/recipe/client/components/recipe-section.svelte
<script module lang="ts">
  import type { Recipe } from '@/features/recipe/client/api/get-one'

  export interface RecipeIngredientGroupsProps {
    readonly recipeId: number
    readonly baseServings: number
    readonly ingredientGroups: Recipe['ingredientGroups']
    readonly presentation?: 'standalone' | 'embedded'
  }
</script>

<script lang="ts">
  import { formatNumber } from '@/utils/number'
  import { scaleQuantity } from '@/utils/scale-quantity'
  import { UNITS } from '@/utils/units'

  import { useRecipeQuantities } from '../hooks/use-recipe-quantities.svelte'

  import * as styles from './recipe-section.css'

  const { recipeId, baseServings, ingredientGroups, presentation = 'standalone' }: RecipeIngredientGroupsProps = $props()
  const quantities = useRecipeQuantities(
    () => recipeId,
    () => baseServings
  )
</script>

{#each ingredientGroups as group}
  <div class={styles.group}>
    {#if group.groupName}<div class={styles.groupName}>{group.groupName}</div>{/if}
    {#if group.groupIngredients.length > 0}
      <ul class={styles.ingredients[presentation]}>
        {#each group.groupIngredients as groupIngredient (groupIngredient.id)}
          <li class={styles.ingredient}>
            <div class={styles.ingredientLine}>
              <span class={styles.bullet}></span>
              <div class={styles.ingredientName}>{groupIngredient.ingredient.name}</div>
              <div class={styles.quantity}>
                {formatNumber(scaleQuantity(groupIngredient.quantity, quantities.quantity, baseServings))}{groupIngredient.unitSlug
                  ? ` ${UNITS[groupIngredient.unitSlug]?.name ?? ''}`
                  : ''}
              </div>
            </div>
          </li>
        {/each}
      </ul>
    {/if}
  </div>
{/each}

// apps/web/src/features/recipe/components/recipe-section.tsx
import { type Recipe } from '@client/features/recipe/api/get-one'
import { useRecipeQuantities } from '@client/features/recipe/hooks/use-recipe-quantities'
import { formatNumber } from '@client/utils/number'
import { UNITS } from '@recipe-organizer/shared/units'
import { scaleQuantity } from '@recipe-organizer/shared/utils/scale-quantity'

import * as styles from './recipe-section.css'

export interface RecipeIngredientGroupsProps {
  readonly recipeId: number
  readonly baseServings: number
  readonly ingredientGroups: Recipe['ingredientGroups']
  readonly presentation?: 'standalone' | 'embedded'
}

export const RecipeIngredientGroups = ({ recipeId, baseServings, ingredientGroups, presentation = 'standalone' }: RecipeIngredientGroupsProps) => {
  const { quantity } = useRecipeQuantities(recipeId, baseServings)

  return ingredientGroups.map((group) => (
    <div className={styles.group} key={group.id}>
      {group.groupName && <div className={styles.groupName}>{group.groupName}</div>}

      {group.groupIngredients.length > 0 && (
        <ul className={styles.ingredients[presentation]}>
          {group.groupIngredients.map((groupIngredient) => (
            <li className={styles.ingredient} key={groupIngredient.id}>
              <div className={styles.ingredientLine}>
                <span className={styles.bullet} />
                <div className={styles.ingredientName}>{groupIngredient.ingredient.name}</div>
                <div className={styles.quantity}>
                  {formatNumber(scaleQuantity(groupIngredient.quantity, quantity, baseServings))}
                  {groupIngredient.unitSlug && ` ${UNITS[groupIngredient.unitSlug]?.name ?? ''}`}
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  ))
}
