// src/components/app-error/app-error.tsx
import { Component } from 'react'
import type { ReactNode } from 'react'

import { Button } from '@/components/ui/actions/button/button'

import * as styles from './app-error.css'

const AppErrorScreen = ({ error }: { error: unknown }) => {
  const details = import.meta.env.DEV && error instanceof Error ? error.message : undefined

  return (
    <div className={styles.root} role="alert">
      <h1 className={styles.heading}>Whoops!</h1>
      <div className={styles.body}>
        <h2 className={styles.subheading}>Une erreur est survenue</h2>
        <p>Une erreur est survenue lors du chargement de la page, nous vous suggérons de revenir à la page d'accueil.</p>
      </div>
      {details && (
        <div className={styles.details}>
          <code>{details}</code>
        </div>
      )}
      <Button asLink href="/" size="lg">
        Retour à la page d'accueil
      </Button>
    </div>
  )
}

/** Recovery screen for render errors after client-side navigation between regular pages. */
interface AppErrorBoundaryState {
  error: unknown
}

export class AppErrorBoundary extends Component<{ children: ReactNode }, AppErrorBoundaryState> {
  constructor(props: { children: ReactNode }) {
    super(props)
    this.state = { error: undefined }
  }

  static getDerivedStateFromError(error: unknown) {
    return { error }
  }

  override render() {
    return this.state.error === undefined ? this.props.children : <AppErrorScreen error={this.state.error} />
  }
}

// src/components/app-error/app-error.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  import Button from '@/components/ui/actions/button/button.svelte'

  import * as styles from './app-error.css'

  /** Recovery screen for render errors after client-side navigation between regular pages; key it by pathname to reset. */
  const { children }: { children: Snippet } = $props()
</script>

<svelte:boundary>
  {@render children()}

  {#snippet failed(error: unknown)}
    {@const details = import.meta.env.DEV && error instanceof Error ? error.message : undefined}
    <div class={styles.root} role="alert">
      <h1 class={styles.heading}>Whoops!</h1>
      <div class={styles.body}>
        <h2 class={styles.subheading}>Une erreur est survenue</h2>
        <p>Une erreur est survenue lors du chargement de la page, nous vous suggérons de revenir à la page d'accueil.</p>
      </div>
      {#if details}
        <div class={styles.details}>
          <code>{details}</code>
        </div>
      {/if}
      <Button asLink href="/" size="lg">Retour à la page d'accueil</Button>
    </div>
  {/snippet}
</svelte:boundary>
