// src/features/recipe/components/quantity-controls.tsx
import { MinusIcon, PlusIcon, TrashIcon } from '@phosphor-icons/react'

import { Button } from '@/components/ui/button'
import { addToShoppingList, removeFromShoppingList } from '@/stores/shopping-list.store'
import { cn } from '@/utils/cn'

import { useIsInShoppingList } from '../hooks/use-is-in-shopping-list'
import { useRecipeQuantities } from '../hooks/use-recipe-quantities'

interface QuantityControlsProps {
  readonly recipeId: number
  readonly servings: number
  readonly variant?: 'default' | 'card'
  readonly className?: string
}

export const QuantityControls = ({ recipeId, servings, variant = 'default', className }: QuantityControlsProps) => {
  const isInShoppingList = useIsInShoppingList(recipeId)
  const { decrementQuantity, incrementQuantity, quantity } = useRecipeQuantities(recipeId, servings)

  if (variant === 'card') {
    if (!isInShoppingList) {
      return (
        <Button onClick={() => addToShoppingList(recipeId)}>
          <PlusIcon weight="bold" />
          Ajouter à la liste
        </Button>
      )
    }

    return (
      <div className="flex w-full items-center justify-center gap-2.5 rounded-xl bg-white/15 p-1 ring-1 ring-white/20 backdrop-blur-md ring-inset">
        <Button
          onClick={decrementQuantity}
          disabled={quantity === 1}
          aria-label="Retirer un couvert"
          size="icon-xs"
          variant="secondary"
          className="bg-white/12 text-white hover:bg-white/20"
        >
          <MinusIcon weight="bold" />
        </Button>
        <span className="min-w-18 text-center text-[13px] font-bold text-white tabular-nums">{quantity} couverts</span>
        <Button onClick={incrementQuantity} aria-label="Ajouter un couvert" size="icon-xs">
          <PlusIcon weight="bold" />
        </Button>
        <Button
          onClick={() => removeFromShoppingList(recipeId)}
          aria-label="Retirer de la liste"
          size="icon-xs"
          variant="secondary"
          className="bg-white/12 text-white hover:bg-white/20"
        >
          <TrashIcon />
        </Button>
      </div>
    )
  }

  return (
    <div className={cn('flex items-center justify-between gap-3 rounded-2xl border bg-card p-2 pl-4', className)}>
      <div className="flex items-center gap-3">
        <span className="text-sm font-bold">Couverts</span>
        <div className="flex items-center gap-2">
          <Button disabled={quantity === 1} onClick={decrementQuantity} aria-label="Retirer un couvert" size="icon-sm" variant="outline">
            <MinusIcon />
          </Button>
          <span className="min-w-5 text-center font-bold tabular-nums">{quantity}</span>
          <Button onClick={incrementQuantity} aria-label="Ajouter un couvert" size="icon-sm">
            <PlusIcon />
          </Button>
        </div>
      </div>
      {isInShoppingList ? (
        <Button onClick={() => removeFromShoppingList(recipeId)} variant="destructive-outline">
          <TrashIcon />
          Retirer
        </Button>
      ) : (
        <Button onClick={() => addToShoppingList(recipeId)} variant="secondary">
          <PlusIcon weight="bold" />
          Ajouter
        </Button>
      )}
    </div>
  )
}

// src/features/recipe/client/components/quantity-controls.svelte
<script module lang="ts">
  interface QuantityControlsProps {
    readonly recipeId: number
    readonly servings: number
    readonly variant?: 'default' | 'card'
  }
</script>

<script lang="ts">
  import Button from '@/components/ui/actions/button/button.svelte'
  import { MinusIcon, PlusIcon, TrashIcon } from '@/components/ui/data-display/icons'
  import { useIsInShoppingList } from '@/hooks/use-is-in-shopping-list.svelte'
  import { addToShoppingList, removeFromShoppingList } from '@/stores/shopping-list.store.svelte'

  import { useRecipeQuantities } from '../hooks/use-recipe-quantities.svelte'

  const { recipeId, servings, variant = 'default' }: QuantityControlsProps = $props()
  const membership = useIsInShoppingList(() => recipeId)
  const quantities = useRecipeQuantities(
    () => recipeId,
    () => servings
  )
</script>

{#if variant === 'card'}
  {#if !membership.current}
    <Button onclick={() => addToShoppingList(recipeId)} width="full"><PlusIcon weight="bold" />Ajouter à la liste</Button>
  {:else}
    <div class="quantity-controls-container">
      <Button
        onclick={quantities.decrementQuantity}
        disabled={quantities.quantity === 1}
        aria-label="Retirer un couvert"
        size="icon-xs"
        variant="secondary"><MinusIcon weight="bold" /></Button
      >
      <span class="quantity-controls-text">{quantities.quantity} couverts</span>
      <Button onclick={quantities.incrementQuantity} aria-label="Ajouter un couvert" size="icon-xs" variant="secondary"
        ><PlusIcon weight="bold" /></Button
      >
      <Button onclick={() => removeFromShoppingList(recipeId)} aria-label="Retirer de la liste" size="icon-xs" variant="secondary"
        ><TrashIcon /></Button
      >
    </div>
  {/if}
{:else}
  <div class="quantity-controls-controls-container">
    <div class="quantity-controls-label-group">
      <span class="quantity-controls-controls-label">Couverts</span>
      <div class="quantity-controls-adjustment-controls">
        <Button
          disabled={quantities.quantity === 1}
          onclick={quantities.decrementQuantity}
          aria-label="Retirer un couvert"
          size="icon-sm"
          variant="outline"><MinusIcon /></Button
        >
        <span class="quantity-controls-quantity-display">{quantities.quantity}</span>
        <Button onclick={quantities.incrementQuantity} aria-label="Ajouter un couvert" size="icon-sm"><PlusIcon /></Button>
      </div>
    </div>
    {#if membership.current}
      <Button onclick={() => removeFromShoppingList(recipeId)} variant="destructive-outline"><TrashIcon />Retirer</Button>
    {:else}
      <Button onclick={() => addToShoppingList(recipeId)} variant="secondary"><PlusIcon weight="bold" />Ajouter</Button>
    {/if}
  </div>
{/if}

<style>
  .quantity-controls-container {
    align-items: center;
    background: var(--colors-primary);
    border-radius: var(--radius-xl);
    display: flex;
    gap: 10px;
    justify-content: center;
    padding: 4px;
    outline: 1;
    outline-color: var(--colors-primary);
    width: 100%;
  }

  .quantity-controls-text {
    color: var(--colors-inverse-foreground);
    font-size: var(--font-sizes-sm);
    font-variant-numeric: tabular-nums;
    font-weight: var(--font-weights-bold);
    min-width: 72px;
    text-align: center;
  }

  .quantity-controls-controls-container {
    align-items: center;
    background: var(--colors-card);
    border-radius: var(--radius-2xl);
    border-width: 1px;
    display: flex;
    gap: 12px;
    justify-content: space-between;
    padding: 8px;
    padding-left: 16px;
  }

  .quantity-controls-label-group {
    align-items: center;
    display: flex;
    gap: 12px;
  }

  .quantity-controls-controls-label {
    font-size: var(--font-sizes-sm);
    font-weight: var(--font-weights-bold);
  }

  .quantity-controls-adjustment-controls {
    align-items: center;
    display: flex;
    gap: 8px;
  }

  .quantity-controls-quantity-display {
    font-variant-numeric: tabular-nums;
    font-weight: var(--font-weights-bold);
    min-width: 20px;
    text-align: center;
  }
</style>
