// apps/web/src/features/recipe/components/recipe-details.tsx
import { deleteRecipeOptions } from '@client/features/recipe/api/delete'
import type { Recipe } from '@client/features/recipe/api/get-one'
import { QuantityControls } from '@client/features/recipe/components/quantity-controls'
import { RecipeIngredientGroups } from '@client/features/recipe/components/recipe-section'
import { RecipeStepGroups } from '@client/features/recipe/components/steps/recipe-steps'
import { alertError } from '@client/lib/alert-error'
import { Badge } from '@recipe-organizer/design-system/badge'
import { Button } from '@recipe-organizer/design-system/button'
import { DeleteDialog } from '@recipe-organizer/design-system/delete-dialog'
import { DotsThreeVerticalIcon } from '@recipe-organizer/design-system/icons/dots-three-vertical'
import { PencilSimpleIcon } from '@recipe-organizer/design-system/icons/pencil-simple'
import { Popover } from '@recipe-organizer/design-system/popover'
import { Skeleton } from '@recipe-organizer/design-system/skeleton'
import { Tabs } from '@recipe-organizer/design-system/tabs'
import { CUISINE_TYPE_LABELS, MAGIMIX_LABEL, MEAL_LABELS, VEGETARIAN_LABEL } from '@recipe-organizer/shared/recipe/constants'
import { incrementalArray } from '@recipe-organizer/shared/utils/array'
import { useMutation } from '@tanstack/react-query'
import { Link, useRouter } from '@tanstack/react-router'

import * as styles from './recipe-details.css'

export const RecipeDetailsSkeleton = () => (
  <>
    <div className={styles.container}>
      <Skeleton preset="recipe-details-title" />
    </div>
    <div className={styles.skeletonDetails}>
      {incrementalArray({ length: 6 }).map((index) => (
        <Skeleton preset="recipe-details-text" key={index} />
      ))}
    </div>
  </>
)

export const RecipeManagementActions = ({ recipe }: { readonly recipe: Recipe }) => {
  const { mutateAsync: deleteRecipe } = useMutation(deleteRecipeOptions())
  const router = useRouter()

  const handleDelete = () =>
    deleteRecipe(
      { data: recipe.id },
      {
        onError: (error) => alertError('Une erreur est survenue lors de la suppression de la recette', error),
        onSuccess: () => router.navigate({ to: '/' }),
      }
    )

  return (
    <Popover
      trigger={
        <Button size="icon" variant="ghost">
          <DotsThreeVerticalIcon weight="bold" />
        </Button>
      }
    >
      <div className={styles.managementActions}>
        <Button
          align="start"
          render={<Link params={{ id: recipe.id.toString() }} to="/recipe/edit/$id" viewTransition />}
          variant="list-action"
          width="full"
        >
          <PencilSimpleIcon size="sm" />
          Modifier la recette
        </Button>
        <DeleteDialog
          deleteButtonLabel="Supprimer la recette"
          description={`Êtes-vous sûr de vouloir supprimer la recette ${recipe.name}?`}
          onDelete={handleDelete}
          title="Supprimer la recette"
          trigger={<Button variant="destructive-ghost" />}
        />
      </div>
    </Popover>
  )
}

export const RecipeDetailsContent = ({ recipe, recipeId }: { readonly recipe: Recipe; readonly recipeId: number }) => {
  const ingredientGroups = [
    ...recipe.ingredientGroups,
    ...recipe.linkedRecipes.map(({ linkedRecipe }) => ({ ...linkedRecipe.ingredientGroups[0], groupName: linkedRecipe.name, isDefault: false })),
  ]
  const metaTags = [
    recipe.isVegetarian && VEGETARIAN_LABEL,
    recipe.isMagimix && MAGIMIX_LABEL,
    ...recipe.meals.map((meal) => MEAL_LABELS[meal]),
    ...recipe.cuisineTypes.map((cuisineType) => CUISINE_TYPE_LABELS[cuisineType]),
  ].filter((tag) => tag !== false)

  return (
    <>
      <h1 className={styles.heading}>{recipe.name}</h1>
      {metaTags.length > 0 && (
        <div className={styles.metadataTags}>
          {metaTags.map((label) => (
            <Badge key={label} size="sm" variant="secondary">
              {label}
            </Badge>
          ))}
        </div>
      )}
      <div className={styles.quantityControls}>
        <QuantityControls recipeId={recipeId} servings={recipe.servings} />
      </div>
      <div className={styles.detailsContent}>
        <div className={styles.mobileTabs}>
          <Tabs
            items={[
              {
                content: (
                  <div className={styles.ingredientsPanel}>
                    <RecipeIngredientGroups
                      recipeId={recipe.id}
                      baseServings={recipe.servings}
                      ingredientGroups={ingredientGroups}
                      presentation="standalone"
                    />
                  </div>
                ),
                label: 'Ingrédients',
                value: 'ingredients',
              },
              {
                content: (
                  <div className={styles.instructionsPanel}>
                    <RecipeStepGroups stepGroups={recipe.stepGroups} />
                  </div>
                ),
                label: 'Préparation',
                value: 'preparation',
              },
            ]}
          />
        </div>
        <div className={styles.desktopLayout}>
          <section className={styles.section}>
            <h2 className={styles.ingredientsHeading}>Ingrédients</h2>
            <RecipeIngredientGroups recipeId={recipeId} baseServings={recipe.servings} ingredientGroups={ingredientGroups} presentation="embedded" />
          </section>
          <section className={styles.instructionsSection}>
            <h2 className={styles.instructionsHeading}>Préparation</h2>
            <div className={styles.instructionsContent}>
              <RecipeStepGroups stepGroups={recipe.stepGroups} />
            </div>
          </section>
        </div>
      </div>
    </>
  )
}

// src/features/recipe/client/components/recipe-details.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'

  import type { Recipe } from '../api/get-one'
  import type { RecipeIngredientGroupsProps } from './recipe-section.svelte'
  import type { SubrecipeInstructions } from './steps/recipe-steps.svelte'

  interface RecipeDetailsContentProps {
    readonly recipe: Recipe
    readonly subrecipes: readonly SubrecipeInstructions[]
    readonly quantityControls: Snippet
    readonly renderIngredientGroups: Snippet<[RecipeIngredientGroupsProps]>
  }
</script>

<script lang="ts">
  import Badge from '@/components/ui/data-display/badge/badge.svelte'
  import Tabs from '@/components/ui/navigation/tabs/tabs.svelte'
  import { CUISINE_TYPE_LABELS, MAGIMIX_LABEL, MEAL_LABELS, VEGETARIAN_LABEL } from '@/features/recipe/constants'

  import RecipeStepGroups from './steps/recipe-steps.svelte'

  import * as styles from './recipe-details.css'

  const { quantityControls, recipe, renderIngredientGroups, subrecipes }: RecipeDetailsContentProps = $props()
  const ingredientGroups = $derived([
    ...recipe.ingredientGroups,
    ...recipe.linkedRecipes.map(({ linkedRecipe }) => ({ ...linkedRecipe.ingredientGroups[0], groupName: linkedRecipe.name, isDefault: false })),
  ])
  const metaTags = $derived(
    [
      recipe.isVegetarian && VEGETARIAN_LABEL,
      recipe.isMagimix && MAGIMIX_LABEL,
      ...recipe.meals.map((meal) => MEAL_LABELS[meal]),
      ...recipe.cuisineTypes.map((cuisineType) => CUISINE_TYPE_LABELS[cuisineType]),
    ].filter((tag) => tag !== false)
  )
</script>

{#snippet ingredientsLabel()}Ingrédients{/snippet}
{#snippet preparationLabel()}Préparation{/snippet}
{#snippet ingredientsPanel()}
  <div class={styles.ingredientsPanel}>
    {@render renderIngredientGroups({ baseServings: recipe.servings, ingredientGroups, presentation: 'standalone', recipeId: recipe.id })}
  </div>
{/snippet}
{#snippet preparationPanel()}
  <div class={styles.instructionsPanel}><RecipeStepGroups stepGroups={recipe.stepGroups} {subrecipes} /></div>
{/snippet}
<h1 class={styles.heading}>{recipe.name}</h1>
{#if metaTags.length > 0}<div class={styles.metadataTags}>
    {#each metaTags as label (label)}<Badge size="sm" variant="secondary">{label}</Badge>{/each}
  </div>{/if}
<div class={styles.quantityControls}>{@render quantityControls()}</div>
<div class={styles.detailsContent}>
  <div class={styles.mobileTabs}>
    <Tabs
      items={[
        { content: ingredientsPanel, label: ingredientsLabel, value: 'ingredients' },
        { content: preparationPanel, label: preparationLabel, value: 'preparation' },
      ]}
    />
  </div>
  <div class={styles.desktopLayout}>
    <section class={styles.section}>
      <h2 class={styles.ingredientsHeading}>Ingrédients</h2>
      {@render renderIngredientGroups({ baseServings: recipe.servings, ingredientGroups, presentation: 'embedded', recipeId: recipe.id })}
    </section>
    <section class={styles.instructionsSection}>
      <h2 class={styles.instructionsHeading}>Préparation</h2>
      <div class={styles.instructionsContent}><RecipeStepGroups stepGroups={recipe.stepGroups} {subrecipes} /></div>
    </section>
  </div>
</div>
