// apps/web/src/features/recipe/components/search-bar.tsx
import { Button } from '@client/components/ui/button'
import { Kbd, KbdGroup } from '@client/components/ui/kbd'
import { useIsMobile } from '@client/hooks/use-is-mobile'
import { usePlatform } from '@client/hooks/use-platfom'
import { lazy, Suspense, useEffect, useRef, useState } from 'react'

const SearchCommandPalette = lazy(() => import('./search-command-palette'))

const SearchBar = () => {
  const [requested, setRequested] = useState(false)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const isMobile = useIsMobile()
  const platform = usePlatform()

  useEffect(() => {
    if (isMobile) {
      return () => undefined
    }

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key.toLowerCase() === 'k' && (event.metaKey || event.ctrlKey)) {
        event.preventDefault()
        setRequested((open) => !open)
      }
    }

    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [isMobile])

  if (isMobile) {
    return null
  }

  return (
    <>
      <Button
        aria-keyshortcuts="Meta+K Control+K"
        aria-label="Rechercher une recette"
        className="w-56 justify-start pl-2.5 font-normal shadow-none"
        onClick={() => setRequested(true)}
        ref={triggerRef}
        variant="outline"
      >
        Recherche une recette...
        <KbdGroup aria-hidden="true" className="absolute top-1.5 right-1.5 gap-1">
          <Kbd>{platform === 'macOS' ? '⌘' : 'Ctrl'}</Kbd>
          <Kbd className="aspect-square">K</Kbd>
        </KbdGroup>
      </Button>
      {requested && (
        <Suspense fallback={null}>
          <SearchCommandPalette finalFocus={triggerRef} onClose={() => setRequested(false)} />
        </Suspense>
      )}
    </>
  )
}

export default SearchBar

// src/features/recipe/client/components/search-bar.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import Button from '@/components/ui/actions/button/button.svelte'
  import KbdGroup from '@/components/ui/data-display/kbd/kbd-group.svelte'
  import Kbd from '@/components/ui/data-display/kbd/kbd.svelte'
  import Dialog from '@/components/ui/overlays/dialog/dialog.svelte'
  import { usePlatform } from '@/hooks/use-platform.svelte'

  import SearchPalette from './search-palette.private.svelte'

  let open = $state(false)
  const platform = usePlatform()
  const down = (event: KeyboardEvent) => {
    if (event.key === 'k' && (event.metaKey || event.ctrlKey)) {
      event.preventDefault()
      open = !open
    }
  }
  onMount(() => {
    document.addEventListener('keydown', down)
    return () => document.removeEventListener('keydown', down)
  })
</script>

<div class="search-bar-container">
  <Dialog bare onOpenChange={(next) => (open = next)} {open} title="Rechercher une recette">
    {#snippet renderTrigger(props)}<Button {...props} align="start" variant="outline" width="full">
        Recherche une recette...
        <span class="search-bar-text"
          ><KbdGroup><Kbd>{platform.current === 'macOS' ? '⌘' : 'Ctrl'}</Kbd><span class="search-bar-shortcut-key"><Kbd>K</Kbd></span></KbdGroup
          ></span
        >
      </Button>{/snippet}
    <SearchPalette onClose={() => (open = false)} />
  </Dialog>
</div>

<style>
  .search-bar-container {
    width: 224px;
  }

  .search-bar-text {
    display: flex;
    position: absolute;
    right: 6px;
    top: 50%;
    translate: 0 -50%;
  }

  .search-bar-shortcut-key {
    aspect-ratio: 1 / 1;
  }
</style>
