// src/features/recipe/client/components/steps/magimix-step-item.svelte
<script lang="ts">
  import { SpinnerGapIcon, ThermometerIcon, TimerIcon } from '@/components/ui/data-display/icons'
  import Item from '@/components/ui/data-display/item/item.svelte'
  import { magimixProgramLabels } from '@/features/recipe/magimix'
  import type { MagimixProgramData } from '@/features/recipe/magimix'
  import { capitalize } from '@/utils/string'

  import * as styles from './magimix-step-item.css'

  const { program, rotationSpeed, temperature, time }: MagimixProgramData = $props()
  const formatTime = (value: number) => {
    const minutes = Math.floor(value / 60)
    const seconds = value % 60
    if (minutes === 0) {
      return `${seconds}s`
    }
    if (seconds === 0) {
      return `${minutes}min`
    }
    return `${minutes}min ${seconds}s`
  }
</script>

<Item variant="outline">
  {#snippet title()}{magimixProgramLabels[program]}{/snippet}
  {#snippet media()}<img alt="" class={styles.image} src={`/magimix/${program}.png`} />{/snippet}
  <TimerIcon size="sm" /><span>{formatTime(time)}</span>/<SpinnerGapIcon size="sm" /><span>{capitalize(rotationSpeed)}</span>
  {#if temperature !== undefined}/<ThermometerIcon size="sm" /><span>{temperature}°C</span>{/if}
</Item>

// apps/web/src/features/recipe/components/steps/magimix-step-item.tsx
import { capitalize } from '@client/utils/string'
import { SpinnerGapIcon, ThermometerIcon, TimerIcon } from '@recipe-organizer/design-system/icons'
import { Item } from '@recipe-organizer/design-system/item'
import { magimixProgramLabels } from '@recipe-organizer/shared/recipe/magimix'
import type { MagimixProgramData } from '@recipe-organizer/shared/recipe/magimix'

import * as styles from './magimix-step-item.css'

const formatTime = (time: number): string => {
  const minutes = Math.floor(time / 60)
  const seconds = time % 60
  if (minutes === 0) {
    return `${seconds}s`
  }
  if (seconds === 0) {
    return `${minutes}min`
  }
  return `${minutes}min ${seconds}s`
}

export const MagimixStepItem = ({ program, rotationSpeed, temperature, time }: MagimixProgramData) => (
  <Item media={<img alt="" className={styles.image} src={`/magimix/${program}.png`} />} title={magimixProgramLabels[program]} variant="outline">
    <TimerIcon size="sm" />
    <span>{formatTime(time)}</span>/
    <SpinnerGapIcon size="sm" />
    <span>{capitalize(rotationSpeed)}</span>
    {temperature !== undefined && (
      <>
        /
        <ThermometerIcon size="sm" />
        <span>{temperature}°C</span>
      </>
    )}
  </Item>
)
