// packages/design-system/src/ui/navigation/tabbar/tabbar.tsx
import { Link } from '@tanstack/react-router'
import type React from 'react'

import { type NavbarProps } from '../navbar/navbar'

import * as styles from './tabbar.css'

export interface TabBarProps {
  items: readonly (NavbarProps['items'][number] & {
    activeIcon: React.ReactNode
    icon: React.ReactNode
  })[]
}

export const TabBar = ({ items }: TabBarProps): React.ReactElement => (
  <nav className={styles.element} data-slot="tab-bar">
    {items.map((item) => (
      <Link {...item.linkProps} className={styles.tabBarItem} data-slot="tab-bar-item" key={item.linkProps.to}>
        <span aria-hidden="true" className={styles.iconSlot} data-slot="tab-bar-item-icon-inactive">
          {item.icon}
        </span>
        <span aria-hidden="true" className={styles.activeIconSlot} data-slot="tab-bar-item-icon-active">
          {item.activeIcon}
        </span>
        {item.label}
      </Link>
    ))}
  </nav>
)

// src/components/navigation/tabbar.svelte
<script lang="ts">
  import { Link } from '@void/svelte'

  import { isCurrentPath } from './current-path'
  import type { MenuItem } from './menu-items.svelte'

  import * as styles from './tabbar.css'

  interface Props {
    currentPath: string
    items: readonly Pick<MenuItem, 'activeIcon' | 'href' | 'icon' | 'label'>[]
  }

  const { currentPath, items }: Props = $props()
</script>

<nav class={styles.element} data-slot="tab-bar">
  {#each items as item (item.href)}
    <Link
      aria-current={isCurrentPath(currentPath, item.href) ? 'page' : undefined}
      class={styles.tabBarItem}
      data-slot="tab-bar-item"
      href={item.href}
      viewTransition={false}
    >
      <span aria-hidden="true" class={styles.iconSlot} data-slot="tab-bar-item-icon-inactive">
        {@render item.icon()}
      </span>
      <span aria-hidden="true" class={styles.activeIconSlot} data-slot="tab-bar-item-icon-active">
        {@render item.activeIcon()}
      </span>
      {item.label}
    </Link>
  {/each}
</nav>
