// packages/design-system/src/ui/overlays/popover/popover.tsx
import { useDrawer } from '@design-system/hooks/use-drawer'
import { useIsMobile } from '@design-system/hooks/use-is-mobile'
import { useEffect, useRef, useState } from 'react'
import type { ReactElement, ReactNode } from 'react'
import { createPortal } from 'react-dom'

import * as drawerStyles from '../drawer/drawer.css'
import * as styles from './popover.css'

export interface PopoverProps {
  children: ReactNode
  trigger: ReactElement
}

/** Exit transition of the anchored popover. */
const POPOVER_ENDING_MS = 150
const SIDE_OFFSET = 4
const COLLISION_PADDING = 8

export const Popover = ({ trigger, children }: PopoverProps): ReactElement => {
  const isMobile = useIsMobile()
  const [open, setOpen] = useState(false)
  const { backdropRef, mounted, phaseProps, popupRef } = useDrawer({
    endingMs: isMobile ? undefined : POPOVER_ENDING_MS,
    onOpenChange: setOpen,
    open,
    swipeable: isMobile,
  })
  const triggerRef = useRef<HTMLSpanElement>(null)
  // Set by React pointer events, which also bubble from nested portals (e.g. a dialog opened from the popover).
  const insideRef = useRef(false)
  const markInside = (): void => {
    insideRef.current = true
  }

  useEffect(() => {
    if (!open) {
      return undefined
    }
    insideRef.current = false
    const onPointerDown = (): void => {
      if (!insideRef.current) {
        setOpen(false)
      }
      insideRef.current = false
    }
    document.addEventListener('pointerdown', onPointerDown)
    return () => document.removeEventListener('pointerdown', onPointerDown)
  }, [open])

  /** Anchors the positioner below the trigger while it is mounted. */
  const anchorPositioner = (positioner: HTMLDivElement): (() => void) | undefined => {
    const anchor = triggerRef.current?.firstElementChild
    if (!anchor) {
      return undefined
    }
    const update = (): void => {
      const rect = anchor.getBoundingClientRect()
      const top = rect.bottom + SIDE_OFFSET
      positioner.style.top = `${top}px`
      positioner.style.left = `${rect.left + rect.width / 2}px`
      positioner.style.setProperty('--available-height', `${window.innerHeight - top - COLLISION_PADDING}px`)
    }
    update()
    window.addEventListener('resize', update)
    window.addEventListener('scroll', update, true)
    return () => {
      window.removeEventListener('resize', update)
      window.removeEventListener('scroll', update, true)
    }
  }

  return (
    <>
      <span className={styles.trigger} onClick={() => setOpen(!open)} onPointerDown={markInside} ref={triggerRef}>
        {trigger}
      </span>
      {mounted &&
        createPortal(
          isMobile ? (
            <>
              <div className={drawerStyles.backdrop()} data-slot="drawer-backdrop" ref={backdropRef} {...phaseProps} />
              <div className={drawerStyles.viewport()} data-slot="drawer-viewport">
                <div className={drawerStyles.popup()} data-slot="drawer-popup" onPointerDown={markInside} ref={popupRef} {...phaseProps}>
                  {children}
                  <div className={drawerStyles.bar()} data-slot="drawer-bar" />
                </div>
              </div>
            </>
          ) : (
            <div className={styles.positioner()} data-slot="popover-positioner" ref={anchorPositioner}>
              <div className={styles.popup()} data-slot="popover-popup" onPointerDown={markInside} {...phaseProps}>
                <div className={styles.viewport()} data-slot="popover-viewport">
                  {children}
                </div>
              </div>
            </div>
          ),
          document.body
        )}
    </>
  )
}

// src/components/ui/overlays/popover/popover.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'

  import type { TriggerProps } from '@/hooks/use-drawer.svelte'

  interface PopoverProps {
    children: Snippet
    onOpenChange?: (open: boolean) => void
    open?: boolean
    renderTrigger: Snippet<[TriggerProps]>
  }
</script>

<script lang="ts">
  import { useDrawer } from '@/hooks/use-drawer.svelte'
  import { useIsMobile } from '@/hooks/use-is-mobile.svelte'

  import { portal } from '../portal.svelte'

  import * as drawerStyles from '../drawer.css'
  import * as styles from './popover.css'

  const { children, onOpenChange, open, renderTrigger }: PopoverProps = $props()
  const mobile = useIsMobile()
  const drawer = useDrawer(() => ({
    endingMs: mobile.current ? undefined : 150,
    modal: mobile.current,
    onOpenChange,
    open,
    swipeable: mobile.current,
  }))
  const anchorPositioner = (positioner: HTMLDivElement) => {
    const anchor = drawer.trigger
    if (!anchor) {
      return
    }
    const update = () => {
      const rect = anchor.getBoundingClientRect()
      const top = rect.bottom + 4
      positioner.style.top = `${top}px`
      positioner.style.left = `${rect.left + rect.width / 2}px`
      positioner.style.setProperty('--anchor-width', `${rect.width}px`)
      positioner.style.setProperty('--available-height', `${window.innerHeight - top - 8}px`)
    }
    update()
    window.addEventListener('resize', update)
    window.addEventListener('scroll', update, true)
    return () => {
      window.removeEventListener('resize', update)
      window.removeEventListener('scroll', update, true)
    }
  }
</script>

{@render renderTrigger(drawer.triggerProps(true))}
{#if drawer.client && drawer.mounted}
  {#if mobile.current}
    <div class={drawerStyles.backdrop} data-slot="drawer-backdrop" bind:this={drawer.backdrop} {...drawer.phaseProps} {@attach portal}></div>
    <div class={drawerStyles.viewport} data-slot="drawer-viewport" {@attach portal} {@attach drawer.dismissOutside}>
      <div class={drawerStyles.popup} data-slot="drawer-popup" bind:this={drawer.popup} {...drawer.phaseProps} {@attach drawer.trackInside}>
        {@render children()}
        <div class={drawerStyles.bar} data-slot="drawer-bar"></div>
      </div>
    </div>
  {:else}
    <div class={styles.positioner} data-slot="popover-positioner" {@attach portal} {@attach anchorPositioner} {@attach drawer.dismissOutside}>
      <div class={styles.popup} data-slot="popover-popup" bind:this={drawer.popup} {...drawer.phaseProps} {@attach drawer.trackInside}>
        <div class={styles.viewport} data-slot="popover-viewport">{@render children()}</div>
      </div>
    </div>
  {/if}
{/if}
