// src/components/ui/spinner.tsx
import { type IconProps, SpinnerGap } from 'phosphor-solid'
import { splitProps } from 'solid-js'

import { cn } from '@/utils/cn'

export const Spinner = (props: IconProps) => {
  const [local, rest] = splitProps(props, ['class'])
  return <SpinnerGap aria-label="Loading" class={cn('animate-spin', local.class)} role="status" {...rest} />
}

// src/components/ui/primitive/spinner.tsx
import { CircleNotchIcon } from '@phosphor-icons/react'
import type React from 'react'

import { cn } from '@/utils/cn'

export const Spinner = ({ className, ...props }: React.ComponentProps<typeof CircleNotchIcon>): React.ReactElement => (
  <CircleNotchIcon aria-label="Loading" className={cn('animate-spin', className)} role="status" {...props} />
)
