// src/features/ingredients/client/components/add-ingredient.svelte
<script module lang="ts">
  import type { DialogProps } from '@/components/ui/overlays/dialog/dialog.svelte'

  import AddIngredientOption from './add-ingredient-option.svelte'

  interface AddIngredientProps {
    defaultValue?: string
    renderTrigger: DialogProps['renderTrigger']
  }

  export { renderAddIngredientOption }
</script>

<script lang="ts">
  import { useRouter } from '@void/svelte'
  import { untrack } from 'svelte'
  import { fetch } from 'void/client'

  import FormDialog from '@/components/ui/overlays/form-dialog/form-dialog.svelte'
  import type { IngredientFormInput } from '@/features/ingredients/schemas'
  import { alertError } from '@/lib/client/alert-error'
  import { readResponse } from '@/lib/client/api-client'

  import IngredientForm, { getIngredientDefaultValues } from './ingredient-form.svelte'

  const { defaultValue, renderTrigger }: AddIngredientProps = $props()
  const router = useRouter()
  let open = $state(false)
  let ingredientData = $state(untrack(() => getIngredientDefaultValues(defaultValue)))
  let pending = $state(false)
  const setData = <TKey extends keyof IngredientFormInput>(key: TKey, value: IngredientFormInput[TKey]) => {
    ingredientData[key] = value
  }
  const submit = async (event: SubmitEvent) => {
    event.preventDefault()
    if (pending) {
      return
    }
    pending = true
    try {
      await readResponse(fetch('/api/ingredients', { body: ingredientData, method: 'POST' }))
      await router.refresh()
      ingredientData = getIngredientDefaultValues(defaultValue)
      open = false
    } catch (error) {
      alertError(`Erreur lors de la création de l'ingrédient ${ingredientData.name ?? ''}`, error)
    } finally {
      pending = false
    }
  }
</script>

{#snippet renderAddIngredientOption(inputValue: string)}<AddIngredientOption {inputValue} />{/snippet}

<FormDialog {pending} onsubmit={submit} {open} setOpen={(next) => (open = next)} submitLabel="Ajouter" title="Ajouter un ingrédient" {renderTrigger}>
  <IngredientForm data={ingredientData} {setData} {pending} />
</FormDialog>

// apps/web/src/features/ingredients/components/add-ingredient.tsx
import { createIngredientOptions, ingredientSchema } from '@client/features/ingredients/api/create'
import { getIngredientDefaultValues, IngredientForm } from '@client/features/ingredients/components/ingredient-form'
import { Button } from '@recipe-organizer/design-system/button'
import type { DialogProps } from '@recipe-organizer/design-system/dialog'
import { getFormDialog } from '@recipe-organizer/design-system/form-dialog'
import { useAppForm } from '@recipe-organizer/design-system/hooks/use-app-form'
import { PlusIcon } from '@recipe-organizer/design-system/icons/plus'
import { revalidateLogic } from '@tanstack/react-form'
import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'

interface AddIngredientProps {
  defaultValue?: string
  renderTrigger: DialogProps['renderTrigger']
}

const FormDialog = getFormDialog(getIngredientDefaultValues())

export const AddIngredient = ({ defaultValue, renderTrigger }: AddIngredientProps) => {
  const createMutation = useMutation(createIngredientOptions())
  const [open, setOpen] = useState(false)

  const form = useAppForm({
    defaultValues: getIngredientDefaultValues(defaultValue),
    onSubmit: async ({ value }) => {
      await createMutation.mutateAsync(
        {
          data: ingredientSchema.parse(value),
        },
        {
          onSuccess: () => {
            form.reset()
            setOpen(false)
          },
        }
      )
    },
    validationLogic: revalidateLogic(),
    validators: {
      onDynamic: ingredientSchema,
    },
  })

  return (
    <FormDialog form={form} open={open} setOpen={setOpen} submitLabel="Ajouter" title="Ajouter un ingrédient" renderTrigger={renderTrigger}>
      <IngredientForm form={form} />
    </FormDialog>
  )
}

export const renderAddIngredientOption = (inputValue: string) => (
  <AddIngredient
    defaultValue={inputValue}
    key={inputValue}
    renderTrigger={(props) => (
      <Button {...props} size="sm" variant="list-action" width="full" align="start">
        <PlusIcon aria-hidden="true" size="sm" />
        Nouvel ingrédient: {inputValue}
      </Button>
    )}
  />
)
