// src/components/navigation/tabbar.tsx
import { Link } from '@tanstack/solid-router'
import { For, type ValidComponent } from 'solid-js'
import { Dynamic } from 'solid-js/web'

import { menuItems } from './constants'

const items = menuItems.filter((item) => item.display !== 'desktop')

export const TabBar = () => (
  <nav class="fixed bottom-0 z-10 flex h-14 w-full items-center justify-around border-t bg-background px-4 md:hidden">
    <For each={items}>
      {(item) => (
        <Link
          {...item.linkProps}
          activeOptions={item.linkProps.to === '/' ? { exact: true } : undefined}
          activeProps={{ class: 'text-primary' }}
          class="flex h-12 flex-1 flex-col items-center justify-center gap-1 text-xs font-semibold text-muted-foreground"
        >
          <Dynamic class="size-6" component={item.icon as unknown as ValidComponent} />
          {item.label}
        </Link>
      )}
    </For>
  </nav>
)

// src/components/tabbar.tsx
import { cn } from '@/lib/utils'
import { useSearchStore } from '@/stores/search.store'
import { MagnifyingGlassIcon } from '@phosphor-icons/react'
import { Link, useRouterState } from '@tanstack/react-router'
import { menuItems } from './navbar'
import { Button } from './ui/button'
import { InputGroup, InputGroupAddon, InputGroupInput } from './ui/input-group'

export const TabBar = () => {
  const { search, setSearch } = useSearchStore()

  const location = useRouterState({ select: (s) => s.location })

  return (
    <div className="flex flex-col items-center border-t border-border bg-background">
      {location.href === '/search' && (
        <div className="px-4 w-full pt-2">
          <InputGroup>
            <InputGroupInput
              placeholder="Rechercher une recette"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              autoFocus
            />

            <InputGroupAddon>
              <MagnifyingGlassIcon />
            </InputGroupAddon>
          </InputGroup>
        </div>
      )}
      <div className="flex justify-around items-center w-full py-2">
        {menuItems
          .filter((item) => item.display !== 'desktop')
          .map((item) => (
            <Button
              variant="ghost"
              className="rounded-full text-primary hover:text-primary"
              render={
                <Link to={item.linkProps.to} activeProps={{ className: 'bg-accent' }}>
                  {({ isActive }) => (
                    <item.icon
                      className={cn('size-6')}
                      {...(isActive ? item.iconFilledProps : {})}
                    />
                  )}
                </Link>
              }
              key={item.label}
            />
          ))}
      </div>
    </div>
  )
}
