// src/features/users/components/approve-user.tsx
import { useMutation } from '@tanstack/solid-query'
import { createSignal } from 'solid-js'
import Check from '~icons/ph/check'

import { Button } from '@/components/ui/button'
import { approveUserOptions } from '@/features/users/api/approve'

interface ApproveUserProps {
  userId: string
}

export const ApproveUser = (props: ApproveUserProps) => {
  const approveMutation = useMutation(() => approveUserOptions())
  const [isPending, setIsPending] = createSignal(false)

  const handleApprove = async () => {
    setIsPending(true)
    try {
      await approveMutation.mutateAsync({ data: { id: props.userId } })
    } finally {
      setIsPending(false)
    }
  }

  return (
    <Button disabled={isPending()} onClick={handleApprove} size="icon" variant="default">
      <Check />
    </Button>
  )
}

// apps/web/src/features/users/components/approve-user.tsx
import { CheckIcon } from '@client/components/icons/check'
import { Button } from '@client/components/ui/button'
import { approveUserOptions } from '@client/features/users/api/approve'
import { useMutation } from '@tanstack/react-query'
import { useTransition } from 'react'

interface ApproveUserProps {
  userId: string
}

export const ApproveUser = ({ userId }: ApproveUserProps) => {
  const approveMutation = useMutation(approveUserOptions())
  const [isPending, startTransition] = useTransition()

  const handleApprove = () => {
    startTransition(async () => {
      await approveMutation.mutateAsync({ data: { id: userId } })
    })
  }

  return (
    <Button disabled={isPending} onClick={handleApprove} size="icon" variant="default">
      <CheckIcon />
    </Button>
  )
}
