// src/features/users/client/components/users-management.svelte
<script lang="ts">
  import { useForm } from '@void/svelte'
  import type { Snippet } from 'svelte'

  import Button from '@/components/ui/actions/button/button.svelte'
  import Badge from '@/components/ui/data-display/badge/badge.svelte'
  import { PlusIcon } from '@/components/ui/data-display/icons'
  import ItemGroup from '@/components/ui/data-display/item/item-group.svelte'
  import ItemSeparator from '@/components/ui/data-display/item/item-separator.svelte'
  import Item from '@/components/ui/data-display/item/item.svelte'
  import SearchInput from '@/components/ui/forms/search-input/search-input.svelte'
  import SelectField from '@/components/ui/forms/select-field/select-field.svelte'
  import TextField from '@/components/ui/forms/text-field/text-field.svelte'
  import Tabs from '@/components/ui/navigation/tabs/tabs.svelte'
  import FormDialog from '@/components/ui/overlays/form-dialog/form-dialog.svelte'
  import type { UserFormInput, UserStatus } from '@/features/users/schemas'
  import { alertError } from '@/lib/client/alert-error'
  import { useFormActionError } from '@/lib/client/page-action.svelte'
  import type { User } from '@/types/user'

  import ApproveUser from './approve-user.svelte'
  import BlockUser from './block-user.svelte'

  import * as styles from './users-management.css'

  const { users }: { users: Record<UserStatus, readonly User[]> } = $props()
  const userDefaultValues: Required<UserFormInput> = { email: '', role: 'user' }
  const roleOptions = [
    { label: 'Utilisateur', value: 'user' },
    { label: 'Administrateur', value: 'admin' },
  ]
  const roleLabels = new Map([
    ['admin', 'Admin'],
    ['user', 'Utilisateur'],
  ])
  const USER_TAB_LABELS = {
    active: { empty: 'Aucun utilisateur actif.', label: 'Actifs' },
    blocked: { empty: 'Aucun utilisateur bloqué.', label: 'Bloqués' },
    pending: { empty: 'Aucun utilisateur en attente.', label: 'En attente' },
  } satisfies Record<UserStatus, { empty: string; label: string }>
  let open = $state(false)
  let search = $state('')
  const query = $derived(search.trim().toLowerCase())
  const filterUsers = (items: readonly User[]) =>
    items.filter((userItem) => userItem.email.toLowerCase().includes(query) || userItem.role.toLowerCase().includes(query))
  const filteredUsers = $derived({ active: filterUsers(users.active), blocked: filterUsers(users.blocked), pending: filterUsers(users.pending) })
  const form = useForm('/settings/users?create', userDefaultValues)
  useFormActionError(() => form.error, "Erreur lors de la création de l'utilisateur")
  const submit = async (event: SubmitEvent) => {
    event.preventDefault()
    if (form.pending) {
      return
    }
    try {
      await form.post({ preserveState: true })
      if (form.wasSuccessful) {
        form.data.email = ''
        form.data.role = 'user'
        open = false
      }
    } catch (error) {
      alertError(`Erreur lors de la création de l'utilisateur ${form.data.email}`, error)
    }
  }
</script>

{#snippet userList(status: UserStatus)}
  <div class={styles.panel}>
    {#if filteredUsers[status].length === 0}
      <p class={styles.emptyState}>{search ? 'Aucun utilisateur trouvé pour cette recherche.' : USER_TAB_LABELS[status].empty}</p>
    {:else}
      <ItemGroup>
        {#each filteredUsers[status] as userItem, index (userItem.id)}
          <Item layout="row">
            {#snippet actions()}
              {#if status === 'blocked' || status === 'pending'}<ApproveUser userId={userItem.id} />{/if}
              {#if status === 'active' || status === 'pending'}<BlockUser userEmail={userItem.email} userId={userItem.id} />{/if}
            {/snippet}
            {#snippet title()}<span class={styles.userEmail}>{userItem.email}</span><Badge
                variant={userItem.role === 'admin' ? 'default' : 'secondary'}>{roleLabels.get(userItem.role)}</Badge
              >{/snippet}
          </Item>
          {#if index !== filteredUsers[status].length - 1}<ItemSeparator />{/if}
        {/each}
      </ItemGroup>
    {/if}
  </div>
{/snippet}
{#snippet activeLabel()}{USER_TAB_LABELS.active.label}{/snippet}
{#snippet pendingLabel()}{USER_TAB_LABELS.pending.label}{/snippet}
{#snippet blockedLabel()}{USER_TAB_LABELS.blocked.label}{/snippet}
{#snippet activeContent()}{@render userList('active')}{/snippet}
{#snippet pendingContent()}{@render userList('pending')}{/snippet}
{#snippet blockedContent()}{@render userList('blocked')}{/snippet}

<div class={styles.searchBar}>
  <SearchInput placeholder="Rechercher une recette, un ingrédient…" {search} setSearch={(next) => (search = next)} />
  <FormDialog
    errors={form.errors}
    pending={form.pending}
    onsubmit={submit}
    {open}
    setOpen={(next) => (open = next)}
    submitLabel="Ajouter"
    title="Ajouter un utilisateur"
  >
    {#snippet renderTrigger(props)}<Button {...props} aria-label="Ajouter un utilisateur" size="icon-lg" variant="outline"><PlusIcon /></Button
      >{/snippet}
    <TextField
      name="email"
      value={form.data.email}
      onChange={(value) => (form.data.email = value)}
      disabled={form.pending}
      label="Email"
      placeholder="Ex: user@example.com"
    />
    <SelectField
      name="role"
      value={form.data.role}
      onChange={(value) => {
        if (value === 'admin' || value === 'user') form.data.role = value
      }}
      disabled={form.pending}
      items={roleOptions}
      label="Rôle"
    />
  </FormDialog>
</div>
<div class={styles.tabs}>
  <Tabs
    items={[
      { content: activeContent, label: activeLabel, value: 'active' },
      { content: pendingContent, label: pendingLabel, value: 'pending' },
      { content: blockedContent, label: blockedLabel, value: 'blocked' },
    ] satisfies { content: Snippet; label: Snippet; value: string }[]}
  />
</div>

// apps/web/src/features/users/components/users-management.tsx
import { createUserOptions, userSchema } from '@client/features/users/api/create'
import type { UserFormInput } from '@client/features/users/api/create'
import { getUserListOptions } from '@client/features/users/api/get-all'
import { ApproveUser } from '@client/features/users/components/approve-user'
import { BlockUser } from '@client/features/users/components/block-user'
import { Badge } from '@recipe-organizer/design-system/badge'
import { Button } from '@recipe-organizer/design-system/button'
import { getFormDialog } from '@recipe-organizer/design-system/form-dialog'
import { useAppForm } from '@recipe-organizer/design-system/hooks/use-app-form'
import { PlusIcon } from '@recipe-organizer/design-system/icons'
import { Item, ItemGroup, ItemSeparator } from '@recipe-organizer/design-system/item'
import { SearchInput } from '@recipe-organizer/design-system/search-input'
import { Tabs } from '@recipe-organizer/design-system/tabs'
import { revalidateLogic } from '@tanstack/react-form'
import { useMutation, useSuspenseQuery } from '@tanstack/react-query'
import { useSelector } from '@tanstack/react-store'
import React, { useState } from 'react'

import * as styles from './users-management.css'

const USER_TABS = ['active', 'pending', 'blocked'] as const
const userDefaultValues: UserFormInput = {
  email: '',
  role: 'user',
}
const roleOptions = [
  { label: 'Utilisateur', value: 'user' },
  { label: 'Administrateur', value: 'admin' },
]
const FormDialog = getFormDialog(userDefaultValues)
const roleLabels = new Map([
  ['admin', 'Admin'],
  ['user', 'Utilisateur'],
])
type UserStatus = (typeof USER_TABS)[number]
const USER_TAB_LABELS = {
  active: { empty: 'Aucun utilisateur actif.', label: 'Actifs' },
  blocked: { empty: 'Aucun utilisateur bloqué.', label: 'Bloqués' },
  pending: { empty: 'Aucun utilisateur en attente.', label: 'En attente' },
} satisfies Record<UserStatus, { empty: string; label: string }>

const UserList = ({ emptyLabel, search, status }: { emptyLabel: string; search: string; status: UserStatus }) => {
  const { data: users } = useSuspenseQuery(getUserListOptions(status))
  const query = search.trim().toLowerCase()
  const filteredUsers = users.filter((userItem) => userItem.email.toLowerCase().includes(query) || userItem.role.toLowerCase().includes(query))
  if (filteredUsers.length === 0) {
    return <p className={styles.emptyState}>{search ? 'Aucun utilisateur trouvé pour cette recherche.' : emptyLabel}</p>
  }
  const showBlockButton = status === 'active' || status === 'pending'
  return (
    <ItemGroup>
      {filteredUsers.map((userItem, index) => (
        <React.Fragment key={userItem.id}>
          <Item
            layout="row"
            actions={
              <>
                {(status === 'blocked' || status === 'pending') && <ApproveUser userId={userItem.id} />}
                {showBlockButton && <BlockUser userEmail={userItem.email} userId={userItem.id} />}
              </>
            }
            title={
              <>
                <span className={styles.userEmail}>{userItem.email}</span>
                <Badge variant={userItem.role === 'admin' ? 'default' : 'secondary'}>{roleLabels.get(userItem.role)}</Badge>
              </>
            }
          />
          {index !== filteredUsers.length - 1 && <ItemSeparator />}
        </React.Fragment>
      ))}
    </ItemGroup>
  )
}

export const UsersManagement = () => {
  const createMutation = useMutation(createUserOptions())
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState('')
  const form = useAppForm({
    defaultValues: userDefaultValues,
    onSubmit: async ({ value }) => {
      await createMutation.mutateAsync(
        {
          data: userSchema.parse(value),
        },
        {
          onSuccess: () => {
            form.reset()
            setOpen(false)
          },
        }
      )
    },
    validationLogic: revalidateLogic(),
    validators: {
      onDynamic: userSchema,
    },
  })
  const isSubmitting = useSelector(form.store, (state) => state.isSubmitting)
  const { AppField } = form

  return (
    <>
      <div className={styles.searchBar}>
        <SearchInput placeholder="Rechercher une recette, un ingrédient…" search={search} setSearch={setSearch} />
        <FormDialog
          form={form}
          open={open}
          setOpen={setOpen}
          submitLabel="Ajouter"
          title="Ajouter un utilisateur"
          renderTrigger={(props) => (
            <Button {...props} aria-label="Ajouter un utilisateur" size="icon-lg" variant="outline">
              <PlusIcon />
            </Button>
          )}
        >
          <AppField name="email">
            {({ TextField }) => <TextField disabled={isSubmitting} label="Email" placeholder="Ex: user@example.com" />}
          </AppField>
          <AppField name="role">{({ SelectField }) => <SelectField disabled={isSubmitting} items={roleOptions} label="Rôle" />}</AppField>
        </FormDialog>
      </div>
      <div className={styles.tabs}>
        <Tabs
          items={USER_TABS.map((status) => ({
            content: (
              <div className={styles.panel}>
                <React.Suspense fallback={null}>
                  <UserList emptyLabel={USER_TAB_LABELS[status].empty} search={search} status={status} />
                </React.Suspense>
              </div>
            ),
            label: USER_TAB_LABELS[status].label,
            value: status,
          }))}
        />
      </div>
    </>
  )
}
