// packages/design-system/src/ui/navigation/tabs/tabs.tsx
import { Link } from '@tanstack/react-router'
import type React from 'react'

import * as styles from './tabs.css'

// Pure HTML + CSS: panels scroll-snap, tabs are hash links that replace history, and the indicator and active label follow the scroll timeline.

interface TabsItem {
  content: React.ReactNode
  label: React.ReactNode
  value: string
}

export type TabsProps = Pick<React.ComponentProps<'nav'>, 'aria-label'> & { items: readonly TabsItem[] }

export const Tabs = ({ 'aria-label': ariaLabel, items }: TabsProps): React.ReactElement => (
  <div className={styles.root()} data-slot="tabs">
    <nav aria-label={ariaLabel} className={styles.list()} data-slot="tabs-list">
      {items.map(({ label, value }) => (
        <Link className={styles.tab()} data-slot="tabs-tab" hash={value} key={value} replace resetScroll={false} to=".">
          {label}
        </Link>
      ))}
      {/* Must stay the last child: tab and indicator geometry derive from sibling-index() and sibling-count(). */}
      <span aria-hidden className={styles.indicator()} data-slot="tab-indicator" />
    </nav>
    <div className={styles.panels()} data-slot="tabs-panels">
      {items.map(({ content, value }) => (
        <div className={styles.panel()} data-slot="tabs-panel" id={value} key={value}>
          {content}
        </div>
      ))}
    </div>
  </div>
)

// src/components/ui/navigation/tabs/tabs.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  import * as styles from './tabs.css'

  interface TabsItem {
    content: Snippet
    label: Snippet
    value: string
  }
  type TabsProps = Pick<HTMLAttributes<HTMLElement>, 'aria-label'> & { items: readonly TabsItem[] }
  const { 'aria-label': ariaLabel, items }: TabsProps = $props()
  const selectTab = (event: MouseEvent, value: string) => {
    event.preventDefault()
    document.getElementById(value)?.scrollIntoView({ block: 'nearest', inline: 'start' })
    history.replaceState(history.state, '', `#${value}`)
  }
</script>

<div class={styles.root} data-slot="tabs">
  <nav aria-label={ariaLabel} class={styles.list} data-slot="tabs-list">
    {#each items as { label, value } (value)}
      <a class={styles.tab} data-slot="tabs-tab" href={`#${value}`} onclick={(event) => selectTab(event, value)}>{@render label()}</a>
    {/each}
    <!-- Must remain last: indicator geometry derives from sibling-count(). -->
    <span aria-hidden="true" class={styles.indicator} data-slot="tab-indicator">
      <span class={styles.indicatorPill}>
        {#each items as { label, value } (value)}<span class={styles.tab}>{@render label()}</span>{/each}
      </span>
    </span>
  </nav>
  <div class={styles.panels} data-slot="tabs-panels">
    {#each items as { content, value } (value)}
      <div class={styles.panel} data-slot="tabs-panel" id={value}>{@render content()}</div>
    {/each}
  </div>
</div>
