// pages/index.svelte
<script lang="ts">
  import { useShared } from '@void/svelte'

  import { mobileMenuItems } from '@/components/navigation/menu-items.svelte'
  import TabBar from '@/components/navigation/tabbar.svelte'
  import ScreenLayout from '@/components/screen-layout/screen-layout.svelte'
  import QuantityControls from '@/features/recipe/client/components/quantity-controls.svelte'
  import RecipeList from '@/features/recipe/client/components/recipe-list.svelte'

  import type { Props } from './index.server'

  const { recipes }: Props = $props()
  const shared = useShared()
</script>

<ScreenLayout title="Recettes">
  <RecipeList canCreate={Boolean(shared.authUser)} {recipes}>
    {#snippet renderCardAction(recipe)}<QuantityControls recipeId={recipe.id} servings={recipe.servings} variant="card" />{/snippet}
  </RecipeList>
  {#snippet footer()}<TabBar currentPath="/" items={mobileMenuItems} />{/snippet}
</ScreenLayout>

// pages/index.tsx
import { useShared } from '@void/react'

import { mobileMenuItems } from '@/components/navigation/constants'
import { TabBar } from '@/components/navigation/tabbar'
import { ScreenLayout } from '@/components/screen-layout/screen-layout'
import { QuantityControls } from '@/features/recipe/client/components/quantity-controls'
import { RecipeListContent } from '@/features/recipe/client/components/recipe-list'

import type { Props } from './index.server'

export default function RecipeListPage({ recipes }: Props) {
  const { authUser } = useShared()

  return (
    <ScreenLayout title="Recettes" footer={<TabBar currentPath="/" items={mobileMenuItems} />}>
      <RecipeListContent
        canCreate={Boolean(authUser)}
        recipes={recipes}
        renderCardAction={(recipe) => <QuantityControls recipeId={recipe.id} servings={recipe.servings} variant="card" />}
      />
    </ScreenLayout>
  )
}
