// src/components/ui/forms/select/select.svelte
<script lang="ts" generics="TValue extends string">
  import { CheckIcon } from '@/components/ui/data-display/icons/svelte'
  import Popover from '@/components/ui/overlays/popover/popover.svelte'
  import { useIsMobile } from '@/hooks/use-is-mobile.svelte'

  import SelectButton from './select.shared.svelte'

  import * as styles from './select.css'
  import * as shared from './select.shared.css'

  interface SelectProps {
    'aria-invalid'?: boolean
    'aria-describedby'?: string
    disabled?: boolean
    id?: string
    items: { label: string; value: TValue | null }[]
    labelId?: string
    onValueChange: (value: TValue | null) => void
    placeholder?: string
    title?: string
    value: TValue | null | undefined
  }
  const {
    'aria-invalid': ariaInvalid,
    'aria-describedby': ariaDescribedby,
    disabled,
    id,
    items,
    labelId,
    onValueChange,
    placeholder = 'Sélectionner',
    title,
    value,
  }: SelectProps = $props()
  const componentId = $props.id()
  const valueId = `${componentId}-value`
  const mobile = useIsMobile()
  let open = $state(false)
  const selected = $derived(items.find((item) => item.value === (value ?? null)))
</script>

<Popover onOpenChange={(next) => (open = next)} {open}>
  {#snippet renderTrigger(props)}<SelectButton
      {...props}
      aria-invalid={ariaInvalid || undefined}
      aria-describedby={ariaDescribedby}
      aria-labelledby={labelId ? `${labelId} ${valueId}` : undefined}
      {disabled}
      {id}><span id={valueId} class={shared.selectTextState[selected ? 'selected' : 'empty']}>{selected?.label ?? placeholder}</span></SelectButton
    >{/snippet}
  <div class={styles.content}>
    {#if mobile.current}<h2 class={styles.title}>{title ?? placeholder}</h2>{/if}
    <div class={styles.list}>
      {#each items as item (item.value ?? 'none')}<button
          class={styles.item}
          onclick={() => {
            onValueChange(item.value)
            open = false
          }}
          type="button"
          ><span class={styles.label}>{item.label}</span>{#if item === selected}<span class={styles.icon}><CheckIcon size="sm" /></span>{/if}</button
        >{/each}
    </div>
  </div></Popover
>

// src/design-system/ui/forms/select/select.tsx
import { useState } from 'react'
import type { ReactElement } from 'react'

import { useIsMobile } from '@/design-system/hooks/use-is-mobile'
import { CheckIcon } from '@/design-system/ui/data-display/icons'
import { Popover } from '@/design-system/ui/overlays/popover/popover'

import { SelectButton } from './select.shared'

import * as styles from './select.css'
import * as shared from './select.shared.css'

interface SelectOption<TValue extends string> {
  label: string
  value: TValue | null
}

export interface SelectProps<TValue extends string> {
  'aria-invalid'?: boolean
  disabled?: boolean
  id?: string
  items: SelectOption<TValue>[]
  onValueChange: (value: TValue | null) => void
  placeholder?: string
  title?: string
  value: TValue | null | undefined
}

export const Select = <TValue extends string>({
  'aria-invalid': ariaInvalid,
  disabled,
  items,
  onValueChange,
  placeholder = 'Sélectionner',
  title,
  value,
}: SelectProps<TValue>): ReactElement => {
  const isMobile = useIsMobile()
  const [open, setOpen] = useState(false)
  const selected = items.find((item) => item.value === (value ?? null))
  return (
    <Popover
      onOpenChange={setOpen}
      open={open}
      renderTrigger={(props) => (
        <SelectButton {...props} aria-invalid={ariaInvalid || undefined} disabled={disabled}>
          <span className={shared.selectTextState[selected ? 'selected' : 'empty']}>{selected?.label ?? placeholder}</span>
        </SelectButton>
      )}
    >
      <div className={styles.content}>
        {isMobile && <h2 className={styles.title}>{title ?? placeholder}</h2>}
        <div className={styles.list}>
          {items.map((item) => (
            <button
              className={styles.item}
              key={item.value ?? 'none'}
              onClick={() => {
                onValueChange(item.value)
                setOpen(false)
              }}
              type="button"
            >
              <span className={styles.label}>{item.label}</span>
              {item === selected && (
                <span className={styles.icon}>
                  <CheckIcon size="sm" />
                </span>
              )}
            </button>
          ))}
        </div>
      </div>
    </Popover>
  )
}
