// src/components/ui/forms/select/select.shared.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  import { CaretUpDownIcon } from '@/components/ui/data-display/icons'
  import type { TriggerProps } from '@/hooks/use-drawer.svelte'

  import * as styles from './select.shared.css'

  type SelectButtonProps = TriggerProps &
    Pick<HTMLButtonAttributes, 'aria-invalid' | 'aria-describedby' | 'aria-labelledby' | 'disabled' | 'id' | 'aria-label'> & { children: Snippet }
  const { children, ...props }: SelectButtonProps = $props()
</script>

<button {...props} class={styles.selectTrigger} data-slot="select-button" type="button"
  ><span class={`${styles.selectText} ${styles.selectTextState.selected}`}>{@render children()}</span><span class={styles.selectTriggerIcon}
    ><CaretUpDownIcon /></span
  ></button
>

// src/design-system/ui/forms/select/select.shared.tsx
import type { ComponentProps, ReactElement } from 'react'

import type { TriggerProps } from '@/design-system/hooks/use-drawer'
import { CaretUpDownIcon } from '@/design-system/ui/data-display/icons'

import * as styles from './select.shared.css'

type SelectButtonProps = TriggerProps & Pick<ComponentProps<'button'>, 'aria-invalid' | 'children' | 'disabled'>

export const SelectButton = ({ children, ...props }: SelectButtonProps): ReactElement => (
  <button {...props} className={styles.selectTrigger} data-slot="select-button" type="button">
    <span className={`${styles.selectText} ${styles.selectTextState.selected}`}>{children}</span>
    <span className={styles.selectTriggerIcon}>
      <CaretUpDownIcon />
    </span>
  </button>
)
