// src/components/ui/data-display/card/card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  import * as styles from './card.css'

  interface CardProps {
    children?: Snippet
    description?: Snippet
    title?: Snippet
  }
  const { children, description, title }: CardProps = $props()
</script>

<div class={styles.card} data-slot="card">
  {#if title !== undefined || description !== undefined}
    <div class={styles.header} data-slot="card-header">
      {#if title !== undefined}<div class={styles.title} data-slot="card-title">{@render title()}</div>{/if}
      {#if description !== undefined}<div class={styles.description} data-slot="card-description">{@render description()}</div>{/if}
    </div>
  {/if}
  {@render children?.()}
</div>

// packages/design-system/src/ui/data-display/card/card.tsx
import type React from 'react'

import * as styles from './card.css'

export type CardProps = Pick<React.ComponentProps<'div'>, 'children'> & { description?: React.ReactNode; title?: React.ReactNode }

export const Card = ({ children, description, title }: CardProps): React.ReactElement => {
  const hasHeader = title !== undefined || description !== undefined
  return (
    <div className={styles.card} data-slot="card">
      {hasHeader && (
        <div className={styles.header} data-slot="card-header">
          {title !== undefined && (
            <div className={styles.title} data-slot="card-title">
              {title}
            </div>
          )}
          {description !== undefined && (
            <div className={styles.description} data-slot="card-description">
              {description}
            </div>
          )}
        </div>
      )}
      {children}
    </div>
  )
}
