// src/components/ui/form.tsx
import { type ComponentProps, createContext, splitProps } from 'solid-js'

import { cn } from '@/utils/cn'

export const FormErrorsContext = createContext<() => Record<string, string>>(() => ({}))

export const Form = (props: ComponentProps<'form'> & { errors?: Record<string, string> }) => {
  const [local, rest] = splitProps(props, ['class', 'errors', 'children'])

  return (
    <FormErrorsContext.Provider value={() => local.errors ?? {}}>
      <form class={cn('flex w-full flex-col gap-4', local.class)} data-slot="form" {...rest}>
        {local.children}
      </form>
    </FormErrorsContext.Provider>
  )
}

// src/design-system/ui/forms/form/form.tsx
import { createContext } from 'react'
import type React from 'react'

import * as styles from './form.css'

const noErrors: Record<string, string> = {}
export const FormErrorsContext = createContext(noErrors)

export type FormProps = Pick<React.ComponentProps<'form'>, 'children' | 'onSubmit'> & { errors?: Record<string, string> }

export const Form = ({ children, errors, onSubmit }: FormProps): React.ReactElement => (
  <form className={styles.form} data-slot="form" noValidate onSubmit={onSubmit}>
    <FormErrorsContext value={errors ?? noErrors}>{children}</FormErrorsContext>
  </form>
)
