// src/routes/settings/ingredients.tsx
import { useQuery } from '@tanstack/solid-query'
import { createFileRoute } from '@tanstack/solid-router'
import { createMemo, createSignal, For, Show } from 'solid-js'
import Plus from '~icons/ph/plus'

import { ingredientCategoryIcons, ingredientCategoryLabels } from '@/components/ingredient-category'
import { ScreenLayout } from '@/components/layout/screen-layout'
import { SearchInput } from '@/components/search-input'
import { Button } from '@/components/ui/button'
import { Item, ItemGroup, ItemSeparator } from '@/components/ui/item'
import { getIngredientListOptions } from '@/features/ingredients/api/get-all'
import { AddIngredient } from '@/features/ingredients/components/add-ingredient'
import { DeleteIngredient } from '@/features/ingredients/components/delete-ingredient'
import { EditIngredient } from '@/features/ingredients/components/edit-ingredient'
import { IngredientBadge } from '@/features/ingredients/components/ingredient-badge'

const IngredientsManagement = () => {
  const ingredientsQuery = useQuery(() => getIngredientListOptions())
  const [search, setSearch] = createSignal('')

  const context = Route.useRouteContext()

  const filteredIngredients = createMemo(() => {
    const query = search().trim().toLowerCase()
    return (ingredientsQuery.data ?? []).filter(
      (ingredient) => ingredient.name.toLowerCase().includes(query) || ingredient.category.toLowerCase().includes(query)
    )
  })

  return (
    <ScreenLayout title="Ingrédients" withGoBack>
      <div class="sticky top-0 z-10 flex items-center gap-4 bg-muted pb-2">
        <SearchInput search={search()} setSearch={setSearch} />
        <AddIngredient trigger={{ as: Button, children: <Plus />, size: 'icon-lg', variant: 'outline' }} />
      </div>

      <Show
        when={filteredIngredients().length > 0}
        fallback={
          <p class="py-8 text-center text-muted-foreground">
            {search() ? 'Aucun ingrédient trouvé pour cette recherche.' : 'Aucun ingrédient trouvé. Ajoutez-en un pour commencer.'}
          </p>
        }
      >
        <ItemGroup>
          <For each={filteredIngredients()}>
            {(ingredient, index) => (
              <>
                <Item
                  actions={
                    context().isAdmin ? (
                      <>
                        <EditIngredient ingredient={ingredient} />
                        <DeleteIngredient ingredientId={ingredient.id} ingredientName={ingredient.name} />
                      </>
                    ) : undefined
                  }
                  class="flex-nowrap"
                  title={
                    <>
                      <span class="text-nowrap text-ellipsis">{ingredient.name}</span>
                      <IngredientBadge category={ingredient.category} class="aspect-square md:aspect-auto">
                        {ingredientCategoryIcons[ingredient.category]}
                        <span class="hidden md:block">{ingredientCategoryLabels[ingredient.category]}</span>
                      </IngredientBadge>
                    </>
                  }
                />
                <Show when={index() !== filteredIngredients().length - 1}>
                  <ItemSeparator />
                </Show>
              </>
            )}
          </For>
        </ItemGroup>
      </Show>
    </ScreenLayout>
  )
}

const RouteComponent = () => <IngredientsManagement />

export const Route = createFileRoute('/settings/ingredients')({
  component: RouteComponent,
  loader: ({ context }) => context.queryClient.ensureQueryData(getIngredientListOptions()),
})

// apps/web/src/routes/settings/ingredients.tsx
import { ingredientCategoryIcons, ingredientCategoryLabels } from '@client/components/ingredient-category'
import { ScreenLayout } from '@client/components/layout/screen-layout'
import { getIngredientListOptions } from '@client/features/ingredients/api/get-all'
import { AddIngredient } from '@client/features/ingredients/components/add-ingredient'
import { DeleteIngredient } from '@client/features/ingredients/components/delete-ingredient'
import { EditIngredient } from '@client/features/ingredients/components/edit-ingredient'
import { IngredientBadge } from '@client/features/ingredients/components/ingredient-badge'
import { Button } from '@recipe-organizer/design-system/button'
import { PlusIcon } from '@recipe-organizer/design-system/icons/plus'
import { Item, ItemGroup, ItemSeparator } from '@recipe-organizer/design-system/item'
import { glassSurface, SearchInput } from '@recipe-organizer/design-system/search-input'
import { useSuspenseQuery } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import React, { useState } from 'react'

const IngredientsManagement = () => {
  const { data: ingredients } = useSuspenseQuery(getIngredientListOptions())
  const [search, setSearch] = useState('')

  const { isAdmin } = Route.useRouteContext()

  const query = search.trim().toLowerCase()
  const filteredIngredients = ingredients.filter(
    (ingredient) => ingredient.name.toLowerCase().includes(query) || ingredient.category.toLowerCase().includes(query)
  )

  return (
    <ScreenLayout title="Ingrédients" withGoBack>
      <div className="sticky top-(--screen-header-height) z-10 flex shrink-0 items-center gap-4 pb-2 md:top-0 md:bg-muted">
        <SearchInput placeholder="Rechercher une recette, un ingrédient…" search={search} setSearch={setSearch} />
        <AddIngredient>
          <Button className={glassSurface} size="icon-lg" variant="outline">
            <PlusIcon />
          </Button>
        </AddIngredient>
      </div>

      {filteredIngredients.length === 0 ? (
        <p className="py-8 text-center text-muted-foreground">
          {search ? 'Aucun ingrédient trouvé pour cette recherche.' : 'Aucun ingrédient trouvé. Ajoutez-en un pour commencer.'}
        </p>
      ) : (
        <ItemGroup>
          {filteredIngredients.map((ingredient, index) => (
            <React.Fragment key={ingredient.id}>
              <Item
                actions={
                  isAdmin ? (
                    <>
                      <EditIngredient ingredient={ingredient} />
                      <DeleteIngredient ingredientId={ingredient.id} ingredientName={ingredient.name} />
                    </>
                  ) : undefined
                }
                className="flex-nowrap"
                title={
                  <>
                    <span className="text-nowrap text-ellipsis">{ingredient.name}</span>
                    <IngredientBadge category={ingredient.category} className="aspect-square md:aspect-auto">
                      {ingredientCategoryIcons[ingredient.category]}
                      <span className="hidden md:block">{ingredientCategoryLabels[ingredient.category]}</span>
                    </IngredientBadge>
                  </>
                }
              />
              {index !== filteredIngredients.length - 1 && <ItemSeparator />}
            </React.Fragment>
          ))}
        </ItemGroup>
      )}
    </ScreenLayout>
  )
}

const RouteComponent = () => <IngredientsManagement />

export const Route = createFileRoute('/settings/ingredients')({
  component: RouteComponent,
  loader: ({ context }) => context.queryClient.query({ ...getIngredientListOptions(), staleTime: 'static' }),
})
