// src/components/ui/forms/toggle-group-field/toggle-group-field.tsx
import { Toggle } from '@/components/ui/actions/toggle/toggle'

import { Field, FieldError, FieldLabel, useFieldInvalid } from '../field/field'

import * as styles from './toggle-group-field.css'

export interface ToggleGroupFieldProps<TValue extends string> {
  name: string
  value: TValue[]
  onChange: (value: TValue[]) => void
  disabled?: boolean
  items: { label: string; value: TValue }[]
  label?: string
}

export const ToggleGroupField = <TValue extends string>({
  name,
  value: selected,
  onChange,
  disabled,
  items,
  label,
}: ToggleGroupFieldProps<TValue>) => {
  const invalid = useFieldInvalid(name)

  return (
    <Field name={name}>
      {label && <FieldLabel>{label}</FieldLabel>}
      <div className={styles.wrapper}>
        <div className={styles.group} data-slot="toggle-group">
          {items.map(({ label: itemLabel, value }) => (
            <span className={styles.item} key={value}>
              <Toggle
                aria-invalid={invalid || undefined}
                disabled={disabled}
                onPressedChange={(pressed) => onChange(pressed ? [...selected, value] : selected.filter((item) => item !== value))}
                pressed={selected.includes(value)}
              >
                {itemLabel}
              </Toggle>
            </span>
          ))}
        </div>
      </div>
      <FieldError />
    </Field>
  )
}

// src/components/ui/forms/toggle-group-field/toggle-group-field.svelte
<script lang="ts" generics="TValue extends string">
  import Toggle from '@/components/ui/actions/toggle/toggle.svelte'

  import { useFieldInvalid } from '../field/field-context.svelte'
  import FieldError from '../field/field-error.svelte'
  import FieldLabel from '../field/field-label.svelte'
  import Field from '../field/field.svelte'

  import * as styles from './toggle-group-field.css'

  interface ToggleGroupFieldProps {
    name: string
    value: TValue[]
    onChange: (value: TValue[]) => void
    disabled?: boolean
    items: { label: string; value: TValue }[]
    label?: string
  }
  const { name, value: selected, onChange, disabled, items, label }: ToggleGroupFieldProps = $props()
  const invalid = useFieldInvalid(() => name)
  const id = $props.id()
</script>

<Field {name}>
  {#if label}<span {id}><FieldLabel>{label}</FieldLabel></span>{/if}
  <div class={styles.wrapper}>
    <div
      class={styles.group}
      data-slot="toggle-group"
      role="group"
      aria-labelledby={label ? id : undefined}
      aria-describedby={invalid() ? `${id}-error` : undefined}
    >
      {#each items as item (item.value)}<span class={styles.item}
          ><Toggle
            {...{ 'aria-invalid': invalid() || undefined }}
            {disabled}
            onPressedChange={(pressed) => onChange(pressed ? [...selected, item.value] : selected.filter((value) => value !== item.value))}
            pressed={selected.includes(item.value)}>{item.label}</Toggle
          ></span
        >{/each}
    </div>
  </div>
  <FieldError id={`${id}-error`} />
</Field>
