// src/components/ui/overlays/form-dialog/form-dialog.tsx
import type { ReactNode, ComponentProps } from 'react'

import { FormSubmit } from '@/components/ui/forms/form-submit/form-submit'
import { FormErrorsContext } from '@/components/ui/forms/form/form'

import { Dialog } from '../dialog/dialog'
import type { DialogProps } from '../dialog/dialog'
import { DialogFormProvider } from '../dialog/dialog-form.private'

import * as styles from './form-dialog.css'

interface FormDialogProps {
  children: ReactNode
  errors?: Record<string, string>
  pending: boolean
  action?: ComponentProps<'form'>['action']
  onSubmit?: ComponentProps<'form'>['onSubmit']
  open: boolean
  setOpen: (open: boolean) => void
  submitLabel: string
  title: string
  renderTrigger?: DialogProps['renderTrigger']
}

export const FormDialog = ({ children, errors, pending, action, onSubmit, open, setOpen, submitLabel, title, renderTrigger }: FormDialogProps) => (
  <DialogFormProvider
    value={{
      // oxlint-disable-next-line react/no-unstable-nested-components -- Private callback is invoked, not mounted as a component.
      wrap(content) {
        return (
          <form
            action={action}
            className={styles.form}
            noValidate
            onSubmit={(event) => {
              event.stopPropagation()
              onSubmit?.(event)
            }}
          >
            <FormErrorsContext value={errors ?? {}}>{content}</FormErrorsContext>
          </form>
        )
      },
    }}
  >
    <Dialog
      cancelDisabled={pending}
      cancelLabel="Annuler"
      footer={<FormSubmit label={submitLabel} pending={pending} />}
      onOpenChange={setOpen}
      open={open}
      title={title}
      renderTrigger={renderTrigger}
    >
      <div className={styles.fields}>{children}</div>
    </Dialog>
  </DialogFormProvider>
)

// src/components/ui/overlays/form-dialog/form-dialog.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLFormAttributes } from 'svelte/elements'

  import type { DialogProps } from '../dialog/dialog.svelte'

  export type FormDialogProps = Pick<HTMLFormAttributes, 'action' | 'onsubmit'> & {
    children: Snippet
    errors?: Record<string, string>
    pending: boolean
    open: boolean
    setOpen: (open: boolean) => void
    submitLabel: string
    title: string
    renderTrigger?: DialogProps['renderTrigger']
  }
</script>

<script lang="ts">
  import FormSubmit from '@/components/ui/forms/form-submit/form-submit.svelte'
  import FormErrors from '@/components/ui/forms/form/form-errors.svelte'

  import { provideDialogFormFrame } from '../dialog/dialog-form.private.svelte'
  import Dialog from '../dialog/dialog.svelte'

  import * as styles from './form-dialog.css'

  const { children, errors, pending, action, onsubmit, open, setOpen, submitLabel, title, renderTrigger }: FormDialogProps = $props()
  provideDialogFormFrame(() => ({ wrap }))
</script>

{#snippet wrap(content: Snippet)}
  <form
    {action}
    class={styles.form}
    novalidate
    onsubmit={(event) => {
      event.stopPropagation()
      if (pending) {
        event.preventDefault()
        return
      }
      onsubmit?.(event)
    }}
  >
    <FormErrors {errors}>{@render content()}</FormErrors>
  </form>
{/snippet}
<Dialog cancelDisabled={pending} cancelLabel="Annuler" onOpenChange={setOpen} {open} {title} {renderTrigger}>
  {#snippet footer()}<FormSubmit label={submitLabel} {pending} />{/snippet}
  <div class={styles.fields}>{@render children()}</div>
</Dialog>
