// src/components/ui/popover.tsx
import { type JSX, lazy, Show, Suspense } from 'solid-js'

import { type TriggerRender } from '@/components/ui/dialog'
import { useIsMobile } from '@/hooks/use-is-mobile'

export interface PopoverProps {
  trigger: TriggerRender
  children: JSX.Element
}

const PopoverBase = lazy(() => import('@/components/ui/popover.base'))
const PopoverDrawer = lazy(() => import('@/components/ui/popover.drawer'))

export const Popover = (props: PopoverProps) => {
  const isMobile = useIsMobile()

  return (
    <Suspense>
      <Show when={isMobile()} fallback={<PopoverBase {...props} />}>
        <PopoverDrawer {...props} />
      </Show>
    </Suspense>
  )
}

// packages/design-system/src/ui/overlays/popover/popover.tsx
import { useIsMobile } from '@design-system/hooks/use-is-mobile'
import { lazy, Suspense, type ReactElement, type ReactNode } from 'react'

export interface PopoverProps {
  children: ReactNode
  trigger: ReactElement
}

const PopoverBase = lazy(() => import('./popover.base'))
const PopoverDrawer = lazy(() => import('./popover.drawer'))

export const Popover = (props: PopoverProps): ReactElement => {
  const Impl = useIsMobile() ? PopoverDrawer : PopoverBase
  return (
    <Suspense fallback={props.trigger}>
      <Impl {...props} />
    </Suspense>
  )
}
