// apps/web/src/components/dialogs/delete-dialog.tsx
import { TrashIcon } from '@client/components/icons/trash'
import { Button } from '@client/components/ui/button'
import { Dialog } from '@client/components/ui/dialog'
import { Spinner } from '@client/components/ui/spinner'
import { cloneElement, useState, useTransition, type ElementType, type ReactElement } from 'react'

interface DeleteDialogProps {
  actionLabel?: string
  deleteButtonLabel?: string
  description: string
  icon?: ElementType
  onDelete: () => Promise<void> | void
  onOpenChange?: (open: boolean) => void
  open?: boolean
  title: string
  trigger?: ReactElement
}

const DefaultTrigger = <Button size="icon" variant="destructive" />

export const DeleteDialog = ({
  actionLabel = 'Supprimer',
  deleteButtonLabel,
  description,
  icon,
  onDelete,
  onOpenChange: onOpenChangeProp,
  open: openProp,
  title,
  trigger = DefaultTrigger,
}: DeleteDialogProps) => {
  const TriggerIcon = icon ?? TrashIcon
  const [internalOpen, setInternalOpen] = useState(false)
  const isControlled = openProp !== undefined
  const isOpen = isControlled ? openProp : internalOpen
  const setIsOpen = (value: boolean) => {
    if (!isControlled) {
      setInternalOpen(value)
    }
    onOpenChangeProp?.(value)
  }
  const [isLoading, startTransition] = useTransition()

  const handleDelete = () => {
    startTransition(async () => {
      await onDelete()
      setIsOpen(false)
    })
  }

  const triggerNode = isControlled
    ? undefined
    : cloneElement(
        trigger,
        undefined,
        <>
          <TriggerIcon /> {deleteButtonLabel}
        </>
      )

  return (
    <Dialog
      cancelLabel="Annuler"
      footer={
        <Button disabled={isLoading} onClick={handleDelete} variant="destructive">
          {isLoading && <Spinner />} {actionLabel}
        </Button>
      }
      onOpenChange={setIsOpen}
      open={isOpen}
      title={title}
      trigger={triggerNode}
    >
      {description}
    </Dialog>
  )
}

// src/components/dialogs/delete-dialog.tsx
import { createSignal, Show } from 'solid-js'
import Trash from '~icons/ph/trash'

import { Button } from '@/components/ui/button'
import { Dialog, type TriggerConfig } from '@/components/ui/dialog'
import { Spinner } from '@/components/ui/spinner'

interface DeleteDialogProps {
  actionLabel?: string
  deleteButtonLabel?: string
  description: string
  icon?: typeof Trash
  onDelete: () => Promise<void> | void
  onOpenChange?: (open: boolean) => void
  open?: boolean
  title: string
  trigger?: TriggerConfig
}

export const DeleteDialog = (props: DeleteDialogProps) => {
  const [internalOpen, setInternalOpen] = createSignal(false)
  const [isLoading, setIsLoading] = createSignal(false)
  const TriggerIcon = props.icon ?? Trash

  const isControlled = () => props.open !== undefined
  const isOpen = () => (isControlled() ? props.open : internalOpen())

  const setIsOpen = (value: boolean) => {
    if (!isControlled()) {
      setInternalOpen(value)
    }
    props.onOpenChange?.(value)
  }

  const handleDelete = async () => {
    setIsLoading(true)
    try {
      await props.onDelete()
      setIsOpen(false)
    } finally {
      setIsLoading(false)
    }
  }

  const triggerConfig = (): TriggerConfig | undefined =>
    isControlled()
      ? undefined
      : {
          as: Button,
          size: 'icon',
          variant: 'destructive',
          ...props.trigger,
          children: (
            <>
              <TriggerIcon /> {props.deleteButtonLabel}
            </>
          ),
        }

  return (
    <Dialog
      cancelLabel="Annuler"
      footer={
        <Button disabled={isLoading()} onClick={handleDelete} variant="destructive">
          <Show when={isLoading()}>
            <Spinner />
          </Show>{' '}
          {props.actionLabel ?? 'Supprimer'}
        </Button>
      }
      onOpenChange={setIsOpen}
      open={isOpen()}
      title={props.title}
      trigger={triggerConfig()}
    >
      {props.description}
    </Dialog>
  )
}
