// src/components/ui/input.tsx
import type * as React from 'react'

import { Input as InputPrimitive } from '@base-ui-components/react/input'

import { cn } from '@/utils/cn'

type InputProps = Omit<InputPrimitive.Props & React.RefAttributes<HTMLInputElement>, 'size'> & {
  size?: 'default' | 'lg' | 'sm' | number
  unstyled?: boolean
}

const Input = ({ className, size = 'default', unstyled = false, ...props }: InputProps) => (
  <span
    className={
      cn(
        !unstyled &&
          'relative inline-flex w-full rounded-lg border border-input bg-background bg-clip-padding text-base/5 shadow-xs ring-ring/24 transition-shadow before:pointer-events-none before:absolute before:inset-0 before:rounded-[calc(var(--radius-lg)-1px)] not-has-disabled:not-has-focus-visible:not-has-aria-invalid:before:shadow-[0_1px_--theme(--color-black/4%)] has-focus-visible:has-aria-invalid:border-destructive/64 has-focus-visible:has-aria-invalid:ring-destructive/16 has-aria-invalid:border-destructive/36 has-focus-visible:border-ring has-disabled:opacity-64 has-[:disabled,:focus-visible,[aria-invalid]]:shadow-none has-focus-visible:ring-[3px] sm:text-sm dark:bg-input/32 dark:not-in-data-[slot=group]:bg-clip-border dark:has-aria-invalid:ring-destructive/24 dark:not-has-disabled:not-has-focus-visible:not-has-aria-invalid:before:shadow-[0_-1px_--theme(--color-white/8%)]',
        className
      ) || undefined
    }
    data-size={size}
    data-slot="input-control"
  >
    <InputPrimitive
      className={cn(
        `
          w-full min-w-0 rounded-[inherit] px-[calc(--spacing(3)-1px)]
          py-[calc(--spacing(1.5)-1px)] outline-none
          placeholder:text-muted-foreground/64
        `,
        size === 'sm' &&
          `
          px-[calc(--spacing(2.5)-1px)] py-[calc(--spacing(1)-1px)]
        `,
        size === 'lg' && 'py-[calc(--spacing(2)-1px)]',
        props.type === 'search' &&
          `
            [&::-webkit-search-cancel-button]:appearance-none
            [&::-webkit-search-decoration]:appearance-none
            [&::-webkit-search-results-button]:appearance-none
            [&::-webkit-search-results-decoration]:appearance-none
          `,
        props.type === 'file' &&
          `
            text-muted-foreground
            file:me-3 file:bg-transparent file:text-sm file:font-medium
            file:text-foreground
          `
      )}
      data-slot="input"
      size={typeof size === 'number' ? size : undefined}
      {...props}
    />
  </span>
)

export { Input, type InputProps }

// src/components/ui/forms/input/input.svelte
<script module lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'

  type InputProps = Pick<
    HTMLInputAttributes,
    'aria-invalid' | 'aria-describedby' | 'aria-label' | 'disabled' | 'id' | 'name' | 'oninput' | 'placeholder' | 'required' | 'type' | 'value'
  > & { defaultValue?: HTMLInputAttributes['value'] }
</script>

<script lang="ts">
  const { defaultValue, value, ...rest }: InputProps = $props()
</script>

<span class="input-surface" data-slot="input-control"><input {...rest} value={value ?? defaultValue} class="input" data-slot="input" /></span>

<style>
  .input-surface {
    background-color: var(--colors-background);
    background-clip: padding-box;
    -webkit-background-clip: padding-box;
    border-color: var(--colors-input);
    border-radius: var(--radius-lg);
    border-width: 1px;
    box-shadow: var(--shadows-xs);
    color: var(--colors-foreground);
    display: inline-flex;
    font-size: var(--font-sizes-base);
    position: relative;
    transition-duration: 150ms;
    transition-property: box-shadow;
    transition-timing-function: var(--easings-in-out);
    width: 100%;
  }

  .input-surface:has(:autofill) {
    background-color: color-mix(in srgb, var(--colors-foreground) 4%, transparent);
  }

  .input-surface:has(:disabled) {
    opacity: 0.64;
  }

  .input-surface:has(:disabled, :focus-visible, [aria-invalid]) {
    box-shadow: var(--shadows-none);
  }

  .input-surface:has(:focus-visible) {
    border-color: var(--colors-ring);
    box-shadow: var(--shadows-ring);
    border-width: 1px;
  }

  .input-surface:has(:focus-visible):has([aria-invalid='true']) {
    border-color: color-mix(in srgb, var(--colors-destructive) 64%, transparent);
    box-shadow: var(--shadows-ring-invalid);
  }

  .input-surface:has([aria-invalid='true']) {
    border-color: color-mix(in srgb, var(--colors-destructive) 36%, transparent);
  }

  :global(.dark) .input-surface:has(:autofill) {
    background-color: color-mix(in srgb, var(--colors-foreground) 8%, transparent);
  }

  :global(.dark) .input-surface {
    background-clip: border-box;
    -webkit-background-clip: border-box;
  }

  @media screen and (min-width: 640px) {
    .input-surface {
      font-size: var(--font-sizes-sm);
    }
  }

  .input {
    background-color: transparent;
    border-radius: var(--radius-lg);
    height: 34px;
    line-height: 34px;
    min-width: 0px;
    outline: none;
    padding-inline: 11px;
    transition: background-color 5000000s ease-in-out 0s;
    width: 100%;
  }

  .input::-webkit-search-cancel-button,
  .input::-webkit-search-decoration,
  .input::-webkit-search-results-button,
  .input::-webkit-search-results-decoration {
    appearance: none;
    -webkit-appearance: none;
  }

  .input::file-selector-button {
    background-color: transparent;
    color: var(--colors-foreground);
    font-size: var(--font-sizes-sm);
    font-weight: var(--font-weights-medium);
    margin-inline-end: 12px;
  }

  .input[type='file'] {
    color: var(--colors-muted-foreground);
  }

  .input::placeholder,
  .input[data-placeholder] {
    color: color-mix(in srgb, var(--colors-muted-foreground) 72%, transparent);
  }

  @media screen and (min-width: 640px) {
    .input {
      height: 30px;
      line-height: 30px;
    }
  }
</style>
