// src/components/ui/forms/input/input.tsx
import type React from 'react'

import * as surface from './input-surface.css'
import * as styles from './input.css'

export type InputProps = Pick<
  React.ComponentProps<'input'>,
  'aria-invalid' | 'aria-label' | 'defaultValue' | 'disabled' | 'id' | 'onChange' | 'placeholder' | 'type' | 'value'
>

export const Input = (props: InputProps): React.ReactElement => (
  <span className={surface.inputSurface} data-slot="input-control">
    <input {...props} className={styles.input} data-slot="input" />
  </span>
)

// src/components/ui/forms/input/input.svelte
<script module lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'

  export type InputProps = Pick<
    HTMLInputAttributes,
    'aria-invalid' | 'aria-describedby' | 'aria-label' | 'disabled' | 'id' | 'name' | 'oninput' | 'placeholder' | 'required' | 'type' | 'value'
  > & { defaultValue?: HTMLInputAttributes['value'] }
</script>

<script lang="ts">
  import * as surface from './input-surface.css'
  import * as styles from './input.css'

  const { defaultValue, value, ...rest }: InputProps = $props()
</script>

<span class={surface.inputSurface} data-slot="input-control"
  ><input {...rest} value={value ?? defaultValue} class={styles.input} data-slot="input" /></span
>
