// src/features/users/client/components/approve-user.svelte
<script lang="ts">
  import Button from '@/components/ui/actions/button/button.svelte'
  import { CheckIcon } from '@/components/ui/data-display/icons/svelte'
  import { alertError } from '@/lib/client/alert-error'
  import { usePageAction } from '@/lib/client/page-action.svelte'

  const { userId }: { userId: string } = $props()
  const runPageAction = usePageAction()
  let isPending = $state(false)
  const handleApprove = async () => {
    if (isPending) {
      return
    }
    isPending = true
    try {
      await runPageAction('/settings/users?approve', { data: { id: userId } }, "Erreur lors de l'approbation de l'utilisateur")
    } catch (error) {
      alertError("Erreur lors de l'approbation de l'utilisateur", error)
    } finally {
      isPending = false
    }
  }
</script>

<Button aria-label="Approuver l'utilisateur" disabled={isPending} onclick={handleApprove} size="icon" variant="default"><CheckIcon /></Button>

// src/features/users/client/components/approve-user.tsx
import { useState } from 'react'

import { Button } from '@/components/ui/actions/button/button'
import { CheckIcon } from '@/components/ui/data-display/icons'
import { usePageAction } from '@/lib/client/page-action'

interface ApproveUserProps {
  userId: string
}

export const ApproveUser = ({ userId }: ApproveUserProps) => {
  const runPageAction = usePageAction()
  const [isPending, setIsPending] = useState(false)

  const handleApprove = async () => {
    setIsPending(true)
    try {
      await runPageAction('/settings/users?approve', { data: { id: userId } }, "Erreur lors de l'approbation de l'utilisateur")
    } catch (error) {
      setIsPending(false)
      throw error
    }
    setIsPending(false)
  }

  return (
    <Button aria-label="Approuver l'utilisateur" disabled={isPending} onClick={handleApprove} size="icon" variant="default">
      <CheckIcon />
    </Button>
  )
}
