// src/components/ui/overlays/delete-dialog/delete-dialog.tsx
import { useState } from 'react'
import type { ElementType, ReactElement, ReactNode } from 'react'

import { Button } from '@/components/ui/actions/button/button'
import { TrashIcon } from '@/components/ui/data-display/icons'
import { Spinner } from '@/components/ui/feedback/spinner/spinner'
import type { TriggerProps } from '@/hooks/use-drawer'

import { Dialog } from '../dialog/dialog'

export interface DeleteDialogProps {
  actionLabel?: string
  deleteButtonLabel?: string
  description: string
  icon?: ElementType
  onDelete: () => Promise<void> | void
  onOpenChange?: (open: boolean) => void
  open?: boolean
  title: string
  renderTrigger?: (props: TriggerProps & { children: ReactNode }) => ReactElement
}

const defaultTrigger: NonNullable<DeleteDialogProps['renderTrigger']> = (props) => <Button {...props} size="icon" variant="destructive" />

export const DeleteDialog = ({
  actionLabel = 'Supprimer',
  deleteButtonLabel,
  description,
  icon,
  onDelete,
  onOpenChange: onOpenChangeProp,
  open: openProp,
  title,
  renderTrigger = defaultTrigger,
}: DeleteDialogProps): ReactElement => {
  const TriggerIcon = icon ?? TrashIcon
  const [internalOpen, setInternalOpen] = useState(false)
  const isControlled = openProp !== undefined
  const isOpen = isControlled ? openProp : internalOpen
  const setIsOpen = (value: boolean) => {
    if (!isControlled) {
      setInternalOpen(value)
    }
    onOpenChangeProp?.(value)
  }
  const [isLoading, setIsLoading] = useState(false)

  const handleDelete = async () => {
    setIsLoading(true)
    try {
      await onDelete()
      setIsOpen(false)
    } catch (error) {
      setIsLoading(false)
      throw error
    }
    setIsLoading(false)
  }

  const triggerNode = isControlled
    ? undefined
    : (props: TriggerProps) =>
        renderTrigger({
          ...props,
          children: (
            <>
              <TriggerIcon /> {deleteButtonLabel}
            </>
          ),
        })

  return (
    <Dialog
      cancelDisabled={isLoading}
      cancelLabel="Annuler"
      footer={
        <Button disabled={isLoading} onClick={handleDelete} variant="destructive">
          {isLoading && <Spinner />} {actionLabel}
        </Button>
      }
      onOpenChange={setIsOpen}
      open={isOpen}
      title={title}
      renderTrigger={triggerNode}
    >
      {description}
    </Dialog>
  )
}

// src/components/ui/overlays/delete-dialog/delete-dialog.svelte
<script module lang="ts">
  import type { Component, Snippet } from 'svelte'

  import type { IconProps } from '@/components/ui/data-display/icons/icon-types'
  import type { TriggerProps } from '@/hooks/use-drawer.svelte'

  interface DeleteDialogProps {
    actionLabel?: string
    deleteButtonLabel?: string
    description: string
    icon?: Component<IconProps>
    onDelete: () => Promise<void> | void
    onOpenChange?: (open: boolean) => void
    open?: boolean
    title: string
    renderTrigger?: Snippet<[TriggerProps & { children: Snippet }]>
  }
</script>

<script lang="ts">
  import Button from '@/components/ui/actions/button/button.svelte'
  import { TrashIcon } from '@/components/ui/data-display/icons'
  import Spinner from '@/components/ui/feedback/spinner/spinner.svelte'

  import Dialog from '../dialog/dialog.svelte'

  const {
    actionLabel = 'Supprimer',
    deleteButtonLabel,
    description,
    icon: TriggerIcon = TrashIcon,
    onDelete,
    onOpenChange,
    open,
    title,
    renderTrigger,
  }: DeleteDialogProps = $props()
  let internalOpen = $state(false)
  const isControlled = $derived(open !== undefined)
  const isOpen = $derived(open ?? internalOpen)
  let isLoading = $state(false)
  const setOpen = (next: boolean) => {
    if (!isControlled) {
      internalOpen = next
    }
    onOpenChange?.(next)
  }
  const handleDelete = async () => {
    if (isLoading) {
      return
    }
    isLoading = true
    try {
      await onDelete()
      setOpen(false)
    } finally {
      isLoading = false
    }
  }
</script>

{#snippet triggerChildren()}<TriggerIcon /> {deleteButtonLabel}{/snippet}
{#snippet trigger(props: TriggerProps)}
  {#if renderTrigger}{@render renderTrigger({ ...props, children: triggerChildren })}
  {:else}<Button {...props} size="icon" variant="destructive">{@render triggerChildren()}</Button>{/if}
{/snippet}

<Dialog
  cancelDisabled={isLoading}
  cancelLabel="Annuler"
  onOpenChange={setOpen}
  open={isOpen}
  {title}
  renderTrigger={isControlled ? undefined : trigger}
>
  {description}
  {#snippet footer()}<Button disabled={isLoading} onclick={handleDelete} variant="destructive"
      >{#if isLoading}<Spinner />{/if}
      {actionLabel}</Button
    >{/snippet}
</Dialog>
