// src/design-system/ui/forms/form/form.tsx
import { createContext } from 'react'
import type React from 'react'

import * as styles from './form.css'

const noErrors: Record<string, string> = {}
export const FormErrorsContext = createContext(noErrors)

export type FormProps = Pick<React.ComponentProps<'form'>, 'children' | 'onSubmit'> & { errors?: Record<string, string> }

export const Form = ({ children, errors, onSubmit }: FormProps): React.ReactElement => (
  <form className={styles.form} data-slot="form" noValidate onSubmit={onSubmit}>
    <FormErrorsContext value={errors ?? noErrors}>{children}</FormErrorsContext>
  </form>
)

// src/components/ui/forms/form/form.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLFormAttributes } from 'svelte/elements'

  type FormProps = Pick<HTMLFormAttributes, 'action' | 'onsubmit'> & { errors?: Record<string, string>; children: Snippet }
</script>

<script lang="ts">
  import { provideFormErrors } from './form-context.svelte'

  import * as styles from './form.css'

  const { action, children, errors, onsubmit }: FormProps = $props()
  provideFormErrors(() => errors)
</script>

<form {action} class={styles.form} data-slot="form" novalidate {onsubmit}>{@render children()}</form>
