// packages/design-system/src/ui/forms/form/form.tsx
import { Form as FormPrimitive } from '@base-ui/react/form'
import type React from 'react'

import * as styles from './form.css'

export type FormProps = Pick<FormPrimitive.Props, 'children' | 'errors' | 'noValidate' | 'onSubmit'>

export const Form = ({ children, errors, noValidate, onSubmit }: FormProps): React.ReactElement => (
  <FormPrimitive className={styles.form} data-slot="form" errors={errors} noValidate={noValidate} onSubmit={onSubmit}>
    {children}
  </FormPrimitive>
)

// src/components/ui/forms/form/form.svelte
<script module lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLFormAttributes } from 'svelte/elements'

  type FormProps = Pick<HTMLFormAttributes, 'action' | 'onsubmit'> & { errors?: Record<string, string>; children: Snippet }
</script>

<script lang="ts">
  import { provideFormErrors } from './form-context.svelte'

  import * as styles from './form.css'

  const { action, children, errors, onsubmit }: FormProps = $props()
  provideFormErrors(() => errors)
</script>

<form {action} class={styles.form} data-slot="form" novalidate {onsubmit}>{@render children()}</form>
