// pages/(app)/recipe/new/index.tsx
import { revalidateLogic } from '@tanstack/react-form'
import { useSelector } from '@tanstack/react-store'
import { useRouter } from '@void/react'

import { useAppForm } from '@/design-system/hooks/use-app-form'
import { Button } from '@/design-system/ui/actions/button/button'
import { Form } from '@/design-system/ui/forms/form/form'
import { GoBackButton, ScreenLayout } from '@/design-system/ui/layout/screen-layout/screen-layout'
import { formatFormErrors } from '@/design-system/utils/format-form-errors'
import { renderAddIngredientOption } from '@/features/ingredients/client/components/add-ingredient'
import { IngredientCatalogProvider } from '@/features/ingredients/client/contexts/ingredient-catalog-context'
import { useIngredientOptions } from '@/features/ingredients/client/hooks/use-ingredient-options'
import { RecipeForm } from '@/features/recipe/client/components/recipe-form'
import { RecipeFormActions } from '@/features/recipe/client/components/recipe-form-actions'
import { RecipeCatalogProvider } from '@/features/recipe/client/contexts/recipe-catalog-context'
import { recipeDefaultValues, recipeFormFields } from '@/features/recipe/client/utils/form'
import { recipeSchema } from '@/features/recipe/schemas'
import { usePageAction } from '@/lib/client/page-action'
import { objectToFormData } from '@/utils/form-data'

import type { Props } from './index.server'

export default function NewRecipePage({ ingredients, recipes }: Props) {
  return (
    <IngredientCatalogProvider ingredients={ingredients}>
      <RecipeCatalogProvider recipes={recipes}>
        <NewRecipeForm />
      </RecipeCatalogProvider>
    </IngredientCatalogProvider>
  )
}

const NewRecipeForm = () => {
  const runPageAction = usePageAction()
  const router = useRouter()
  const ingredientOptions = useIngredientOptions()

  const form = useAppForm({
    defaultValues: recipeDefaultValues,
    onSubmit: async ({ value }) => {
      const succeeded = await runPageAction(
        '/recipe/new',
        { data: Object.fromEntries(objectToFormData(value)) },
        `Erreur lors de la création de la recette ${value.name ?? ''}`
      )
      if (succeeded) {
        await router.visit('/')
      }
    },
    validationLogic: revalidateLogic(),
    validators: {
      onDynamic: recipeSchema,
    },
  })

  const errors = useSelector(form.store, (state) => formatFormErrors(state.errors))

  return (
    <ScreenLayout title="Nouvelle Recette" backButton={<GoBackButton />}>
      <Form
        errors={errors}
        onSubmit={(event) => {
          event.preventDefault()
          void form.handleSubmit()
        }}
      >
        <RecipeForm addNewIngredientOption={renderAddIngredientOption} fields={recipeFormFields} form={form} ingredientOptions={ingredientOptions} />
        <RecipeFormActions>
          <Button disabled={form.state.isSubmitting} onClick={() => router.visit('/')} type="button" variant="outline">
            Annuler
          </Button>
          <form.AppForm>
            <form.FormSubmit label="Créer la recette" />
          </form.AppForm>
        </RecipeFormActions>
      </Form>
    </ScreenLayout>
  )
}

// pages/recipe/new/index.svelte
<script lang="ts">
  import { useForm, useRouter } from '@void/svelte'

  import GoBackButton from '@/components/screen-layout/go-back-button.svelte'
  import ScreenLayout from '@/components/screen-layout/screen-layout.svelte'
  import Button from '@/components/ui/actions/button/button.svelte'
  import FormSubmit from '@/components/ui/forms/form-submit/form-submit.svelte'
  import Form from '@/components/ui/forms/form/form.svelte'
  import { renderAddIngredientOption } from '@/features/ingredients/client/components/add-ingredient.svelte'
  import { provideIngredientCatalog } from '@/features/ingredients/client/contexts/ingredient-catalog-context.svelte'
  import { useIngredientOptions } from '@/features/ingredients/client/hooks/use-ingredient-options.svelte'
  import RecipeFormActions from '@/features/recipe/client/components/recipe-form-actions.svelte'
  import type { RecipeFormState } from '@/features/recipe/client/components/recipe-form.svelte'
  import RecipeForm from '@/features/recipe/client/components/recipe-form.svelte'
  import { provideRecipeCatalog } from '@/features/recipe/client/contexts/recipe-catalog-context.svelte'
  import { recipeDefaultValues } from '@/features/recipe/client/utils/form'
  import { alertError } from '@/lib/client/alert-error'
  import { useFormActionError } from '@/lib/client/page-action.svelte'

  import type { Props } from './index.server'

  const { ingredients, recipes }: Props = $props()
  provideIngredientCatalog(() => ingredients)
  provideRecipeCatalog(() => recipes)
  const ingredientOptions = useIngredientOptions()
  const router = useRouter()

  const form = useForm('/recipe/new', recipeDefaultValues)
  const errorMessage = () => `Erreur lors de la création de la recette ${form.data.name ?? ''}`
  useFormActionError(() => form.error, errorMessage)
  const recipeForm: RecipeFormState = {
    get data() {
      return form.data
    },
    get pending() {
      return form.pending
    },
    setData: (key, value) => {
      form.data[key] = value
    },
  }

  const submit = async (event: SubmitEvent) => {
    event.preventDefault()
    if (form.pending) {
      return
    }
    try {
      await form.post()
      if (form.wasSuccessful) {
        await router.visit('/', { replace: true })
      }
    } catch (error) {
      alertError(errorMessage(), error)
    }
  }
</script>

<ScreenLayout title="Nouvelle Recette">
  <Form errors={form.errors} onsubmit={submit}>
    <RecipeForm addNewIngredientOption={renderAddIngredientOption} form={recipeForm} ingredientOptions={ingredientOptions.current} />
    <RecipeFormActions>
      <Button disabled={form.pending} onclick={() => router.visit('/')} type="button" variant="outline">Annuler</Button>
      <FormSubmit pending={form.pending} label="Créer la recette" />
    </RecipeFormActions>
  </Form>
  {#snippet backButton()}<GoBackButton />{/snippet}
</ScreenLayout>
