// src/components/ui/data-display/card/card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface CardProps {
    children?: Snippet
    description?: Snippet
    title?: Snippet
  }
  const { children, description, title }: CardProps = $props()
</script>

<div class="card" data-slot="card">
  {#if title !== undefined || description !== undefined}
    <div class="header" data-slot="card-header">
      {#if title !== undefined}<div class="title" data-slot="card-title">{@render title()}</div>{/if}
      {#if description !== undefined}<div class="description" data-slot="card-description">{@render description()}</div>{/if}
    </div>
  {/if}
  {@render children?.()}
</div>

<style>
  .card {
    background-clip: padding-box;
    -webkit-background-clip: padding-box;
    background-color: var(--colors-card);
    border-radius: var(--radius-2xl);
    border-width: 1px;
    color: var(--colors-card-foreground);
    display: flex;
    flex-direction: column;
    position: relative;
    box-shadow: var(--shadows-xs);
  }
  :global(.dark) .card {
    background-clip: border-box;
    -webkit-background-clip: border-box;
  }

  .header {
    align-items: start;
    display: grid;
    gap: 6px;
    grid-auto-rows: min-content;
    grid-template-rows: auto auto;
    padding: 24px;
  }

  .title {
    font-size: var(--font-sizes-lg);
    font-weight: var(--font-weights-semibold);
    line-height: var(--line-heights-none);
  }

  .description {
    color: var(--colors-muted-foreground);
    font-size: var(--font-sizes-sm);
  }
</style>

// src/components/ui/card.tsx
import { cn } from 'cn'
import { type ReactElement, type ReactNode } from 'react'

interface CardProps {
  title?: ReactNode
  description?: ReactNode
  className?: string
  children?: ReactNode
}

export const Card = ({ title, description, className, children }: CardProps): ReactElement => {
  const hasHeader = title !== undefined || description !== undefined

  return (
    <div
      className={cn(`relative flex flex-col rounded-2xl border bg-card text-card-foreground shadow-xs/5 not-dark:bg-clip-padding`, className)}
      data-slot="card"
    >
      {hasHeader && (
        <div className="grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 p-6" data-slot="card-header">
          {title !== undefined && (
            <div className="text-lg leading-none font-semibold" data-slot="card-title">
              {title}
            </div>
          )}
          {description !== undefined && (
            <div className="text-sm text-muted-foreground" data-slot="card-description">
              {description}
            </div>
          )}
        </div>
      )}
      {children}
    </div>
  )
}
