// src/components/ui/primitive/item.tsx
import { mergeProps } from '@base-ui/react/merge-props'
import { useRender } from '@base-ui/react/use-render'
import { cva, type VariantProps } from 'class-variance-authority'

import { Separator } from '@/components/ui/primitive/separator'
import { cn } from '@/utils/cn'

const ItemGroup = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn('group/item-group flex flex-col', className)} data-slot="item-group" role="list" {...props} />
)

const ItemSeparator = ({ className, ...props }: React.ComponentProps<typeof Separator>) => (
  <Separator className={cn('my-0', className)} data-slot="item-separator" orientation="horizontal" {...props} />
)

const itemVariants = cva(
  `
    group/item flex flex-wrap items-center rounded-md border border-transparent
    text-sm transition-colors duration-100 outline-none
    focus-visible:border-ring focus-visible:ring-[3px]
    focus-visible:ring-ring/50
    [a]:transition-colors [a]:hover:bg-accent/50
  `,
  {
    defaultVariants: {
      size: 'default',
      variant: 'default',
    },
    variants: {
      size: {
        default: 'gap-4 p-4',
        sm: 'gap-2.5 px-4 py-3',
      },
      variant: {
        default: 'bg-transparent',
        muted: 'bg-muted/50',
        outline: 'border-border',
      },
    },
  }
)

const Item = ({
  className,
  render,
  size = 'default',
  variant = 'default',
  ...props
}: React.ComponentProps<'div'> & VariantProps<typeof itemVariants> & { render?: useRender.RenderProp }) =>
  useRender({
    defaultTagName: 'div',
    props: mergeProps(
      {
        className: cn(itemVariants({ className, size, variant })),
        'data-size': size,
        'data-slot': 'item',
        'data-variant': variant,
      },
      props
    ),
    render,
  })

const itemMediaVariants = cva(
  `
    flex shrink-0 items-center justify-center gap-2
    group-has-[[data-slot=item-description]]/item:translate-y-0.5
    group-has-[[data-slot=item-description]]/item:self-start
    [&_svg]:pointer-events-none
  `,
  {
    defaultVariants: {
      variant: 'default',
    },
    variants: {
      variant: {
        default: 'bg-transparent',
        icon: `
          size-8 rounded-sm border bg-muted
          [&_svg:not([class*='size-'])]:size-4
        `,
        image: `
          size-10 overflow-hidden rounded-sm
          [&_img]:size-full [&_img]:object-cover
        `,
      },
    },
  }
)

const ItemMedia = ({ className, variant = 'default', ...props }: React.ComponentProps<'div'> & VariantProps<typeof itemMediaVariants>) => (
  <div className={cn(itemMediaVariants({ className, variant }))} data-slot="item-media" data-variant={variant} {...props} />
)

const ItemContent = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn(`flex flex-1 flex-col gap-1 [&+[data-slot=item-content]]:flex-none`, className)} data-slot="item-content" {...props} />
)

const ItemTitle = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn(`flex w-fit items-center gap-2 text-sm leading-snug font-medium`, className)} data-slot="item-title" {...props} />
)

const ItemDescription = ({ className, ...props }: React.ComponentProps<'p'>) => (
  <p
    className={cn(
      `line-clamp-2 text-sm leading-normal font-normal text-balance text-muted-foreground`,
      `[&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary`,
      className
    )}
    data-slot="item-description"
    {...props}
  />
)

const ItemActions = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn('flex items-center gap-2', className)} data-slot="item-actions" {...props} />
)

const ItemHeader = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn('flex basis-full items-center justify-between gap-2', className)} data-slot="item-header" {...props} />
)

const ItemFooter = ({ className, ...props }: React.ComponentProps<'div'>) => (
  <div className={cn('flex basis-full items-center justify-between gap-2', className)} data-slot="item-footer" {...props} />
)

export { Item, ItemActions, ItemContent, ItemDescription, ItemFooter, ItemGroup, ItemHeader, ItemMedia, ItemSeparator, ItemTitle }

// src/components/ui/item.tsx
import { cva, type VariantProps } from 'class-variance-authority'
import { type ComponentProps, type JSX, Show, splitProps } from 'solid-js'

import { Separator } from '@/components/ui/separator'
import { cn } from '@/utils/cn'

export const ItemGroup = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])
  return <div class={cn('group/item-group flex flex-col', local.class)} data-slot="item-group" role="list" {...rest} />
}

export const ItemSeparator = (props: ComponentProps<typeof Separator>) => {
  const [local, rest] = splitProps(props, ['class'])
  return <Separator class={cn('my-0', local.class)} data-slot="item-separator" orientation="horizontal" {...rest} />
}

const itemVariants = cva(
  `
    group/item flex flex-wrap items-center gap-4 rounded-md border border-transparent p-4
    text-sm transition-colors duration-100 outline-none
    focus-visible:border-ring focus-visible:ring-[3px]
    focus-visible:ring-ring/50
    [a]:transition-colors [a]:hover:bg-accent/50
  `,
  {
    defaultVariants: {
      variant: 'default',
    },
    variants: {
      variant: {
        default: 'bg-transparent',
        outline: 'border-border',
      },
    },
  }
)

interface ItemProps {
  media?: JSX.Element
  title?: JSX.Element
  children?: JSX.Element
  actions?: JSX.Element
  variant?: VariantProps<typeof itemVariants>['variant']
  class?: string
}

const itemMediaClass = `
  flex shrink-0 items-center justify-center gap-2 bg-transparent
  group-has-data-[slot=item-description]/item:translate-y-0.5
  group-has-data-[slot=item-description]/item:self-start
  [&_svg]:pointer-events-none
`

export const Item = (props: ItemProps) => {
  const hasContent = () => props.title !== undefined || props.children !== undefined

  return (
    <div class={cn(itemVariants({ variant: props.variant ?? 'default' }), props.class)} data-slot="item">
      <Show when={props.media !== undefined}>
        <div class={itemMediaClass} data-slot="item-media">
          {props.media}
        </div>
      </Show>
      <Show when={hasContent()}>
        <div class="flex flex-1 flex-col gap-1 [&+[data-slot=item-content]]:flex-none" data-slot="item-content">
          <Show when={props.title !== undefined}>
            <div class="flex w-fit items-center gap-2 text-sm leading-snug font-medium" data-slot="item-title">
              {props.title}
            </div>
          </Show>
          <Show when={props.children !== undefined}>
            <p
              class="not-prose flex items-center gap-1 text-sm leading-normal font-normal text-balance text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary"
              data-slot="item-description"
            >
              {props.children}
            </p>
          </Show>
        </div>
      </Show>
      <Show when={props.actions !== undefined}>
        <div class="flex items-center gap-2" data-slot="item-actions">
          {props.actions}
        </div>
      </Show>
    </div>
  )
}
