// apps/web/src/components/ui/skeleton.tsx
import { cn } from 'cn'
import type React from 'react'

export const Skeleton = ({ className, ...props }: React.ComponentProps<'div'>): React.ReactElement => (
  <div
    className={cn(
      'animate-skeleton rounded-sm [--skeleton-highlight:--alpha(var(--color-white)/64%)] [background:linear-gradient(120deg,transparent_40%,var(--skeleton-highlight),transparent_60%)_var(--color-muted)_0_0/200%_100%_fixed] dark:[--skeleton-highlight:--alpha(var(--color-white)/4%)]',
      className
    )}
    data-slot="skeleton"
    {...props}
  />
)

// src/components/ui/skeleton.tsx
import { type ComponentProps, splitProps } from 'solid-js'

import { cn } from '@/utils/cn'

export const Skeleton = (props: ComponentProps<'div'>) => {
  const [local, rest] = splitProps(props, ['class'])
  return (
    <div
      class={cn(
        'animate-skeleton rounded-sm [--skeleton-highlight:--alpha(var(--color-white)/64%)] [background:linear-gradient(120deg,transparent_40%,var(--skeleton-highlight),transparent_60%)_var(--color-muted)_0_0/200%_100%_fixed] dark:[--skeleton-highlight:--alpha(var(--color-white)/4%)]',
        local.class
      )}
      data-slot="skeleton"
      {...rest}
    />
  )
}
