// packages/design-system/src/ui/forms/form-submit/form-submit.tsx
import { useFormContext } from '../../../hooks/use-form-context'
import { Button } from '../../actions/button/button'
import { Spinner } from '../../feedback/spinner/spinner'

export const FormSubmit = ({ label }: { label: string }) => {
  const form = useFormContext()
  return (
    <form.Subscribe>
      {({ isSubmitting }) => (
        <Button disabled={isSubmitting} type="submit">
          {isSubmitting && <Spinner />}
          {label}
        </Button>
      )}
    </form.Subscribe>
  )
}

// src/components/forms/form-submit.tsx
import { Show } from 'solid-js'

import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import { useFormContext } from '@/hooks/use-form-context'

export const FormSubmit = (props: { label: string }) => {
  const form = useFormContext()

  return (
    <form.Subscribe selector={(state) => state.isSubmitting}>
      {(isSubmitting) => (
        <Button disabled={isSubmitting()} type="submit">
          <Show when={isSubmitting()}>
            <Spinner />
          </Show>
          {props.label}
        </Button>
      )}
    </form.Subscribe>
  )
}
