// src/features/shopping-list/client/component/shopping-list.svelte
<script lang="ts">
  import { ingredientCategoryIcons, ingredientCategoryLabels } from '@/components/ingredient-categories'
  import Button from '@/components/ui/actions/button/button.svelte'
  import { BasketIcon } from '@/components/ui/data-display/icons'
  import Skeleton from '@/components/ui/feedback/skeleton/skeleton.svelte'
  import { ingredientCategory } from '@/features/ingredients/categories'
  import { incrementalArray } from '@/utils/array'

  import { useShoppingList } from '../hooks/use-shopping-list.svelte'
  import CartItem from './cart-item.svelte'

  import * as styles from './shopping-list.css'

  const shoppingList = useShoppingList()
  const groups = $derived(
    Object.entries(shoppingList.current).flatMap(([key, ingredients]) => {
      const category = ingredientCategory.find((item) => item === key)
      return category && ingredients?.length ? [{ category, ingredients }] : []
    })
  )
</script>

<div class={styles.list}>
  {#if shoppingList.status === 'pending'}
    {#each incrementalArray({ length: 4 }) as index (index)}
      <div class={styles.container}>
        <Skeleton preset="shopping-list-title" />
        <div class={styles.loadingRows}>
          {#each incrementalArray({ length: 3 }) as innerIndex (innerIndex)}
            <Skeleton preset="shopping-list-row" />
          {/each}
        </div>
      </div>
    {/each}
  {:else if shoppingList.status === 'error'}
    <div class={styles.emptyState}>
      <p role="alert" class={styles.text}>Impossible de charger votre liste de courses. Veuillez réessayer.</p>
      <Button onclick={shoppingList.retry} variant="outline">Réessayer</Button>
    </div>
  {:else if groups.length === 0}
    <div class={styles.emptyState}>
      <div class={styles.emptyStateIcon}><BasketIcon size="xl" /></div>
      <p class={styles.text}>Votre liste de courses est vide</p>
      <p class={styles.emptyStateDescription}>Ajoutez des recettes depuis la recherche</p>
    </div>
  {:else}
    {#each groups as { category, ingredients } (category)}
      {@const Icon = ingredientCategoryIcons[category]}
      <div>
        <h2 class={styles.heading}><Icon />{ingredientCategoryLabels[category]}</h2>
        <div class={styles.categoryCard}>
          {#each ingredients as ingredient (ingredient.id)}
            <CartItem {ingredient} />
          {/each}
        </div>
      </div>
    {/each}
  {/if}
</div>

// src/features/shopping-list/component/shopping-list.tsx
import { ingredientCategoryIcons, ingredientCategoryLabels } from '@client/components/ingredient-category'
import { useIsHydrated } from '@client/hooks/use-is-hydrated'
import { BasketIcon } from '@recipe-organizer/design-system/icons'
import { Skeleton } from '@recipe-organizer/design-system/skeleton'
import { ingredientCategory } from '@recipe-organizer/shared/ingredients/categories'
import { incrementalArray } from '@recipe-organizer/shared/utils/array'
import { Suspense } from 'react'

import { useShoppingList } from '../hooks/use-shopping-list'
import { CartItem } from './cart-item'

import * as styles from './shopping-list.css'

const ShoppingListSkeleton = () =>
  incrementalArray({ length: 4 }).map((index) => (
    <div className={styles.container} key={index}>
      <Skeleton preset="shopping-list-title" />
      <div className={styles.loadingRows}>
        {incrementalArray({ length: 3 }).map((innerIndex) => (
          <Skeleton preset="shopping-list-row" key={innerIndex} />
        ))}
      </div>
    </div>
  ))

const ShoppingListGroups = () => {
  const shoppingListIngredients = useShoppingList()

  const groups = Object.entries(shoppingListIngredients).flatMap(([key, ingredients]) => {
    const category = ingredientCategory.find((item) => item === key)
    return category && ingredients?.length ? [{ category, ingredients }] : []
  })

  if (groups.length === 0) {
    return (
      <div className={styles.emptyState}>
        <div className={styles.emptyStateIcon}>
          <BasketIcon size="xl" />
        </div>
        <p className={styles.text}>Votre liste de courses est vide</p>
        <p className={styles.emptyStateDescription}>Ajoutez des recettes depuis la recherche</p>
      </div>
    )
  }

  return groups.map(({ category: key, ingredients }) => (
    <div key={key}>
      <h2 className={styles.heading}>
        {ingredientCategoryIcons[key]}
        {ingredientCategoryLabels[key]}
      </h2>
      <div className={styles.categoryCard}>
        {ingredients.map((ingredient) => (
          <CartItem ingredient={ingredient} key={ingredient.id} />
        ))}
      </div>
    </div>
  ))
}

export const ShoppingList = () => {
  // The selection lives in localStorage, which server HTML cannot know.
  const isHydrated = useIsHydrated()

  return (
    <div className={styles.list}>
      {isHydrated ? (
        <Suspense fallback={<ShoppingListSkeleton />}>
          <ShoppingListGroups />
        </Suspense>
      ) : (
        <ShoppingListSkeleton />
      )}
    </div>
  )
}
